create table if not exists projects
(
    id                      bigint generated by default as identity
        primary key,
    priority                integer,
    project_completion_date timestamp,
    project_name            varchar(255),
    project_start_date      timestamp,
    project_status          integer
);

create table if not exists tasks
(
    id          bigint generated by default as identity
        primary key,
    description text,
    priority    integer,
    task_name   varchar(255),
    task_status integer,
    project_id  bigint
        references projects
);

create table if not exists projects_tasks
(
    project_id bigint not null
        references projects,
    tasks_id   bigint not null
        unique
        references tasks
);
