TRUNCATE TABLE projects, tasks, projects_tasks RESTART IDENTITY;

insert into projects (priority, project_status, project_start_date, project_name, project_completion_date)
values (84, 2, '2020-12-25 17:49:57', 'adapter', null),
       (99, 2, '2021-08-02 13:27:36', 'object-oriented', '2022-02-01 21:24:38'),
       (34, 1, '2021-03-05 17:09:12', 'non-volatile', '2021-08-03 12:01:42'),
       (97, 2, '2022-01-30 03:09:05', 'Persistent', '2021-07-10 20:52:57'),
       (47, 0, '2021-07-30 12:05:44', 'contingency', null),
       (29, 2, '2021-09-21 11:22:17', 'Intuitive', '2021-07-27 09:26:49'),
       (40, 1, '2021-04-26 16:10:07', 'static', null),
       (8, 2, '2021-05-13 19:14:05', 'orchestration', null),
       (1, 0, '2021-12-10 20:19:37', 'Grass-roots', null),
       (97, 2, '2021-12-16 02:18:25', 'hybrid', '2021-10-28 12:08:05');

insert into tasks (project_id, task_status, task_name, priority, description)
values (1, 2, 'Overhold', 33, 'purus sit amet'),
       (5, 1, 'Bytecard', 40,
        'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor'),
       (1, 1, 'Gembucket', 83, 'nec condimentum neque sapien placerat ante nulla'),
       (4, 0, 'Veribet', 39, 'magnis dis'),
       (9, 0, 'Flowdesk', 71, 'dui'),
       (6, 1, 'Konklux', 31,
        'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis'),
       (6, 0, 'Zathin', 9, 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem'),
       (4, 0, 'Opela', 89, 'pretium iaculis diam erat fermentum'),
       (8, 0, 'Stim', 38,
        'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc'),
       (3, 0, 'Flexidy', 46, 'eget rutrum'),
       (7, 0, 'Tres-Zap', 45, 'dignissim vestibulum vestibulum ante ipsum'),
       (10, 0, 'Holdlamis', 56,
        'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non'),
       (1, 2, 'Cardify', 57,
        'sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse'),
       (9, 0, 'Keylex', 12, 'nulla integer pede'),
       (10, 0, 'Fintone', 35, 'augue luctus tincidunt'),
       (9, 2, 'Namfix', 50,
        'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede'),
       (2, 2, 'Wrapsafe', 41, 'aliquet massa id lobortis convallis tortor'),
       (9, 0, 'Tresom', 69, 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices'),
       (8, 1, 'Tres-Zap', 94,
        'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer'),
       (8, 0, 'Andalax', 55, 'ligula vehicula consequat morbi a ipsum integer'),
       (2, 2, 'Namfix', 56,
        'praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo'),
       (1, 2, 'Tin', 24,
        'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices'),
       (4, 1, 'Tampflex', 23,
        'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim'),
       (8, 1, 'Lotstring', 21, 'fermentum donec ut mauris eget massa tempor convallis nulla neque'),
       (6, 0, 'Sonair', 73,
        'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar'),
       (6, 1, 'Trippledex', 66, 'mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet'),
       (9, 0, 'Voyatouch', 3, 'ut rhoncus'),
       (9, 1, 'Subin', 85, 'rutrum'),
       (7, 2, 'Alpha', 29,
        'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet'),
       (10, 0, 'Bytecard', 10, 'in quam fringilla rhoncus mauris enim leo rhoncus sed'),
       (2, 2, 'Bitwolf', 98, 'ultrices enim lorem ipsum dolor sit'),
       (3, 2, 'Bamity', 81, 'donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac'),
       (7, 2, 'Temp', 100, 'sit amet sem fusce consequat nulla'),
       (3, 1, 'Greenlam', 3, 'vivamus'),
       (4, 0, 'Domainer', 32, 'pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus'),
       (5, 2, 'Ronstring', 73, 'nec dui'),
       (3, 0, 'Voltsillam', 56, 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel'),
       (7, 0, 'Zamit', 45, 'justo eu massa donec dapibus duis'),
       (3, 1, 'Ventosanzap', 88, 'ut odio'),
       (8, 1, 'Tin', 26, 'dictumst'),
       (9, 0, 'Fixflex', 78, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque'),
       (1, 1, 'Lotlux', 80, 'magnis dis parturient montes nascetur'),
       (10, 1, 'Latlux', 5, 'posuere'),
       (2, 1, 'Treeflex', 50, 'suscipit ligula in lacus curabitur at ipsum ac'),
       (8, 0, 'Regrant', 21, 'ornare consequat'),
       (2, 2, 'It', 11,
        'volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec'),
       (9, 0, 'Sub-Ex', 84, 'proin risus praesent lectus vestibulum quam'),
       (4, 0, 'Stim', 8, 'curae mauris viverra diam vitae quam suspendisse potenti nullam'),
       (7, 2, 'Zaam-Dox', 94,
        'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum'),
       (5, 1, 'Fintone', 77, 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci');

-- Join table
insert into projects_tasks (project_id, tasks_id)
select project_id,
       id
from tasks;
