-- TRUNCATE TABLE projects, tasks, projects_tasks RESTART IDENTITY;

-- 100 projects
insert into projects (priority, project_completion_date, project_name, project_start_date, project_status)
values (19, '4/15/2021', 'Leggett''s Pinweed', '12/28/2020', 1),
       (25, '6/18/2021', 'Glossostigma', '1/5/2022', 2),
       (28, null, 'Yellow Evening Primrose', '3/18/2021', 1),
       (1, null, 'Mazus', '1/26/2021', 1),
       (5, '6/7/2021', 'Cloudberry', '2/10/2021', 1),
       (63, null, 'Snow Raspberry', '5/30/2021', 2),
       (16, '5/12/2021', 'Smooth Solomon''s Seal', '6/15/2021', 0),
       (12, '9/11/2021', 'Skin Lichen', '5/14/2021', 0),
       (12, null, 'Forget-me-not', '4/23/2021', 2),
       (66, '1/20/2021', 'East Indian Island Pea', '3/27/2021', 2),
       (1, '12/10/2021', 'Seaside Joyweed', '10/8/2021', 2),
       (9, null, 'Fireweed', '12/4/2021', 1),
       (58, '11/14/2021', 'Balloonbush', '2/1/2022', 1),
       (69, null, 'Lead Lichen', '1/12/2021', 1),
       (64, '12/4/2021', 'Gummy Gooseberry', '10/4/2021', 2),
       (76, '7/13/2021', 'Dactylina Lichen', '2/28/2021', 0),
       (74, '6/5/2021', 'Parana Pine', '1/5/2021', 2),
       (32, '11/4/2021', 'Heldreich''s Alfalfa', '4/28/2021', 1),
       (5, null, 'Goosefoot Violet', '8/15/2021', 0),
       (69, null, 'Cuero De Rana', '9/12/2021', 2),
       (82, null, 'Mountain Magnolia', '7/17/2021', 1),
       (61, null, 'Whiskerbrush', '6/16/2021', 1),
       (53, null, 'Marsh Rose Gentian', '2/23/2021', 0),
       (73, null, 'Sharplobe Hepatica', '3/17/2021', 0),
       (4, '4/8/2021', 'Pacific Anemone', '9/10/2021', 0),
       (41, null, 'Sweet Breath Of Spring', '7/13/2021', 2),
       (12, null, 'Canadian Hawkweed', '5/7/2021', 0),
       (55, '9/16/2021', 'North Coast Semaphoregrass', '12/22/2021', 2),
       (95, null, 'Skiff Milkvetch', '3/11/2021', 0),
       (78, null, 'Hoary Blackfoot', '3/24/2021', 1),
       (13, '4/2/2021', 'Nichol''s Echinocactus', '7/24/2021', 2),
       (7, null, 'Spreading Stickseed', '8/14/2021', 2),
       (78, null, 'Shorthook Fishhook Cactus', '1/25/2022', 0),
       (46, null, 'Tuerckheimia Moss', '11/14/2021', 0),
       (47, null, 'Wheat', '1/28/2021', 2),
       (46, '6/11/2021', 'Ellipticleaf Papala', '2/6/2021', 1),
       (73, null, 'Dictamnus', '1/6/2021', 2),
       (45, '9/8/2021', 'Strict Blue-eyed Grass', '2/19/2021', 2),
       (87, null, 'Oahu False Ohelo', '3/27/2021', 1),
       (53, null, 'Hemlockparsley', '1/8/2021', 0),
       (65, '12/29/2021', 'Mountain Fetterbush', '2/1/2021', 2),
       (69, null, 'Red Pea', '12/19/2020', 1),
       (90, '1/5/2021', 'Blackbrush', '1/6/2022', 1),
       (11, '1/30/2021', 'Jones'' Lupine', '10/18/2021', 0),
       (56, null, 'Pinedrops', '7/16/2021', 1),
       (69, null, 'Daggerpod', '9/28/2021', 1),
       (42, null, 'Whitethorn Acacia', '12/10/2020', 0),
       (64, '6/8/2021', 'Tumamoca', '11/10/2021', 0),
       (75, null, 'Chaplin''s Golden Columbine', '3/12/2021', 1),
       (61, null, 'Howell''s Broomrape', '9/5/2021', 1),
       (71, '11/10/2021', 'Longleaf Indian Paintbrush', '4/10/2021', 0),
       (32, '1/21/2022', 'Shale Barren Buckwheat', '8/13/2021', 0),
       (36, null, 'Carey''s Balsamroot', '12/7/2021', 2),
       (36, null, 'Rock Nettle', '12/14/2020', 1),
       (48, null, 'Canadian Rush', '1/11/2022', 0),
       (87, '12/12/2021', 'Longspur Lupine', '12/14/2020', 1),
       (81, null, 'Bentflower Milkvetch', '8/24/2021', 1),
       (78, null, 'Thomson''s Porpidia Lichen', '4/2/2021', 1),
       (67, null, 'Barley Mitchell Grass', '6/5/2021', 1),
       (76, null, 'Jopoy', '11/9/2021', 2),
       (61, null, 'Oblongleaf Snakeherb', '3/21/2021', 2),
       (59, null, 'Orthodontium Moss', '12/6/2021', 0),
       (66, '6/11/2021', 'Velvet Leaf Senna', '7/9/2021', 1),
       (71, null, 'Wreath Lichen', '12/5/2020', 1),
       (78, '4/19/2021', 'Cypress Panicgrass', '1/14/2022', 0),
       (91, '2/11/2021', 'Brachythecium Moss', '1/6/2022', 2),
       (42, null, 'False Flowering Spurge', '7/31/2021', 2),
       (71, '1/2/2021', 'Bering Sea Sedge', '12/5/2020', 1),
       (42, '3/20/2021', 'Minute Hawthorn', '4/5/2021', 2),
       (76, null, 'Vulcan Cup Lichen', '1/10/2021', 1),
       (66, null, 'Wildrye', '12/23/2020', 0),
       (92, '12/29/2021', 'Torrey''s Jointfir', '9/3/2021', 1),
       (74, null, 'Christmas Fern', '10/21/2021', 2),
       (31, null, 'Hasse''s Cracked Lichen', '5/15/2021', 0),
       (26, '7/22/2021', 'Balsamscale Grass', '1/17/2022', 0),
       (28, null, 'Mistassini Primrose', '10/25/2021', 0),
       (33, '2/12/2021', 'Maiden Fern', '9/20/2021', 2),
       (43, null, 'Racomitrium Moss', '12/6/2021', 2),
       (63, null, 'Rocketsalad', '9/23/2021', 0),
       (71, null, 'Baker''s Manzanita', '4/27/2021', 2),
       (59, null, 'Tacky Phacelia', '4/16/2021', 2),
       (63, null, 'Parasite Rinodina Lichen', '2/12/2021', 2),
       (92, null, 'Sunbonnets', '7/3/2021', 0),
       (80, null, 'Manystamen Forchhammeria', '6/11/2021', 2),
       (17, '1/22/2022', 'Nuttall''s Saltbush', '11/9/2021', 2),
       (12, '8/14/2021', 'Arctic Snow Lichen', '4/13/2021', 0),
       (46, null, 'Santolina Pincushion', '7/2/2021', 1),
       (43, '1/24/2022', 'Jamaican Fanpetals', '10/9/2021', 0),
       (80, null, 'Farinose Cartilage Lichen', '1/7/2021', 0),
       (57, null, 'American Milkvetch', '5/27/2021', 1),
       (43, null, 'Ashby''s Banksia', '5/28/2021', 2),
       (1, '1/17/2021', 'Piedmont Cowbane', '1/12/2022', 2),
       (6, '1/7/2021', 'Hooker''s Cinquefoil', '12/25/2020', 2),
       (3, null, 'Lespedeza', '1/6/2021', 2),
       (65, null, 'Butterbur', '12/13/2021', 1),
       (68, '5/6/2021', 'Recurved Hypnum Moss', '8/6/2021', 2),
       (33, null, 'Spotted Beebalm', '2/9/2021', 2),
       (93, '9/18/2021', 'False Indian Plantain', '5/21/2021', 0),
       (22, null, 'Munz''s Tidytips', '4/27/2021', 2),
       (56, '2/19/2021', 'Mamani', '12/2/2020', 2);


-- 1000 tasks
insert into tasks (description, priority, task_name, task_status, project_id)
values ('urna ut tellus nulla ut erat id', 66, 'Laniarius ferrugineus', 1, 16),
       ('cubilia curae duis faucibus accumsan odio', 100, 'unavailable', 1, 81),
       ('tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', 13, 'Neotis denhami', 0, 57),
       ('integer ac leo pellentesque', 47, 'Phoenicopterus ruber', 0, 76),
       ('aliquet at feugiat non pretium quis lectus', 96, 'Drymarchon corias couperi', 2, 51),
       ('dapibus duis at velit', 90, 'Pseudoleistes virescens', 0, 87),
       ('vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', 55, 'Coendou prehensilis', 2, 42),
       ('sit amet eleifend pede libero quis orci nullam molestie', 54, 'Odocoilenaus virginianus', 1, 15),
       ('aenean auctor gravida sem praesent id massa id', 12, 'Canis mesomelas', 2, 87),
       ('id lobortis convallis tortor risus dapibus augue vel accumsan', 50, 'Caiman crocodilus', 0, 52),
       ('nec molestie', 77, 'Marmota flaviventris', 1, 82),
       ('in felis donec', 17, 'Bucorvus leadbeateri', 0, 78),
       ('id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 9, 'Terrapene carolina', 0, 79),
       ('risus semper porta volutpat', 42, 'Kobus defassa', 0, 37),
       ('neque duis bibendum', 13, 'Chlamydosaurus kingii', 2, 68),
       ('sed ante vivamus tortor', 15, 'Sciurus niger', 2, 95),
       ('vulputate elementum nullam varius nulla facilisi cras non', 24, 'Phalacrocorax carbo', 1, 9),
       ('imperdiet nullam orci pede', 60, 'Gekko gecko', 0, 18),
       ('sit amet diam', 57, 'Hymenolaimus malacorhynchus', 0, 10),
       ('turpis adipiscing lorem vitae mattis nibh', 26, 'Cervus duvauceli', 2, 8),
       ('penatibus et', 29, 'Anthropoides paradisea', 0, 78),
       ('volutpat dui maecenas tristique est', 39, 'Cercopithecus aethiops', 1, 1),
       ('integer aliquet massa id lobortis convallis tortor risus', 45, 'Paraxerus cepapi', 0, 69),
       ('congue risus semper porta volutpat quam pede', 33, 'Bubalus arnee', 2, 2),
       ('dolor morbi', 8, 'Tockus erythrorhyncus', 1, 10),
       ('integer ac neque', 80, 'Phoeniconaias minor', 2, 11),
       ('nunc purus', 98, 'Gabianus pacificus', 2, 47),
       ('luctus et ultrices posuere cubilia', 78, 'Sylvilagus floridanus', 1, 24),
       ('massa id', 91, 'Panthera leo persica', 1, 92),
       ('luctus et ultrices posuere', 22, 'Felis concolor', 0, 52),
       ('iaculis congue vivamus metus arcu adipiscing molestie hendrerit', 96, 'Threskionis aethiopicus', 2, 96),
       ('quis turpis eget', 84, 'Centrocercus urophasianus', 2, 77),
       ('tellus nisi eu orci', 72, 'Dendrocygna viduata', 2, 68),
       ('nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 76, 'Herpestes javanicus', 2, 67),
       ('varius integer', 86, 'Ara ararauna', 2, 93),
       ('penatibus et magnis dis parturient', 41, 'Egretta thula', 2, 92),
       ('ultrices posuere cubilia curae', 86, 'Lemur fulvus', 2, 1),
       ('leo odio condimentum id luctus', 20, 'Laniarius ferrugineus', 2, 55),
       ('aliquam sit amet diam in magna bibendum imperdiet', 36, 'Trichosurus vulpecula', 1, 51),
       ('id nisl', 90, 'Sarcophilus harrisii', 1, 40),
       ('morbi vel lectus in quam fringilla rhoncus mauris enim', 85, 'Zonotrichia capensis', 2, 29),
       ('in congue etiam justo', 55, 'Coluber constrictor foxii', 2, 66),
       ('nulla justo aliquam quis turpis eget elit sodales scelerisque', 70, 'Upupa epops', 1, 92),
       ('sapien a libero nam dui proin leo odio', 2, 'Phalaropus lobatus', 2, 15),
       ('in felis eu sapien cursus vestibulum proin eu mi nulla', 73, 'Fratercula corniculata', 0, 88),
       ('nulla suspendisse potenti', 43, 'Spermophilus armatus', 2, 59),
       ('montes nascetur ridiculus mus', 70, 'Nyctea scandiaca', 0, 87),
       ('eget vulputate ut ultrices', 56, 'Psittacula krameri', 1, 6),
       ('neque aenean auctor', 44, 'Agkistrodon piscivorus', 1, 61),
       ('suscipit a feugiat et eros vestibulum', 2, 'Snycerus caffer', 1, 9),
       ('luctus tincidunt', 48, 'Bos taurus', 1, 50),
       ('dictumst aliquam augue quam sollicitudin vitae', 82, 'Sciurus niger', 1, 50),
       ('lobortis sapien sapien non mi integer', 43, 'Streptopelia senegalensis', 1, 98),
       ('amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', 1, 'Phalaropus lobatus', 2,
        6),
       ('neque duis bibendum morbi non quam nec dui', 80, 'Graspus graspus', 0, 74),
       ('nec sem duis aliquam convallis nunc proin at', 81, 'Eumetopias jubatus', 0, 50),
       ('vestibulum ante ipsum primis in faucibus orci luctus et', 82, 'Tockus erythrorhyncus', 2, 35),
       ('luctus rutrum nulla tellus', 87, 'unavailable', 0, 89),
       ('interdum mauris', 97, 'Cereopsis novaehollandiae', 0, 10),
       ('venenatis turpis enim blandit mi in porttitor', 3, 'Callorhinus ursinus', 2, 42),
       ('amet cursus id turpis integer aliquet', 24, 'Sula dactylatra', 0, 36),
       ('est phasellus sit', 31, 'Taxidea taxus', 2, 82),
       ('lacus at velit vivamus vel nulla', 12, 'Ictalurus furcatus', 1, 12),
       ('lacinia erat vestibulum sed magna', 40, 'Cygnus buccinator', 1, 24),
       ('aliquam convallis nunc proin at', 42, 'Phascogale calura', 0, 3),
       ('ligula vehicula consequat morbi a ipsum', 38, 'Varanus albigularis', 1, 51),
       ('dictumst etiam faucibus', 57, 'Merops nubicus', 1, 80),
       ('integer tincidunt ante', 36, 'Cervus elaphus', 2, 6),
       ('mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 9, 'Pycnonotus nigricans', 1, 80),
       ('imperdiet nullam orci pede', 58, 'Uraeginthus granatina', 2, 22),
       ('nulla integer pede justo lacinia eget', 48, 'Cynictis penicillata', 2, 70),
       ('pharetra magna ac consequat metus sapien ut nunc vestibulum ante', 6, 'Panthera leo', 2, 13),
       ('tellus nisi eu orci', 29, 'Plegadis ridgwayi', 0, 28),
       ('massa id nisl venenatis lacinia', 50, 'Papio cynocephalus', 2, 76),
       ('praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 55, 'Damaliscus dorcas', 1, 35),
       ('suspendisse potenti nullam', 69, 'Columba palumbus', 1, 48),
       ('mauris morbi non lectus aliquam sit amet', 81, 'Cervus duvauceli', 2, 28),
       ('ipsum aliquam non mauris morbi non lectus aliquam', 26, 'Laniaurius atrococcineus', 0, 1),
       ('habitasse platea dictumst morbi', 89, 'Graspus graspus', 0, 1),
       ('maecenas tincidunt lacus at velit vivamus vel nulla', 92, 'Certotrichas paena', 1, 71),
       ('potenti nullam porttitor lacus at turpis donec', 71, 'Thamnolaea cinnmomeiventris', 0, 28),
       ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 83, 'Phylurus milli', 0, 29),
       ('porttitor pede', 16, 'Speothos vanaticus', 2, 26),
       ('ut odio', 45, 'Paradoxurus hermaphroditus', 2, 46),
       ('vel pede morbi porttitor lorem id ligula suspendisse ornare', 69, 'Gymnorhina tibicen', 0, 70),
       ('donec semper sapien a libero nam dui proin leo odio', 58, 'Pitangus sulphuratus', 2, 60),
       ('non mi integer ac neque duis bibendum morbi non', 49, 'Cynomys ludovicianus', 0, 57),
       ('metus vitae ipsum aliquam non mauris morbi', 3, 'Felis silvestris lybica', 0, 7),
       ('dui nec nisi volutpat', 50, 'Nyctereutes procyonoides', 1, 49),
       ('etiam faucibus cursus urna ut tellus nulla ut erat', 45, 'Pycnonotus nigricans', 0, 80),
       ('pede lobortis', 97, 'Butorides striatus', 1, 19),
       ('dui nec nisi volutpat', 50, 'Proteles cristatus', 0, 37),
       ('curabitur convallis duis consequat dui nec nisi volutpat', 42, 'Mabuya spilogaster', 1, 14),
       ('mauris vulputate elementum nullam varius nulla facilisi cras non velit', 15, 'unavailable', 1, 59),
       ('congue vivamus metus arcu adipiscing molestie hendrerit at', 94, 'Spermophilus lateralis', 1, 54),
       ('habitasse platea dictumst etiam faucibus cursus urna ut tellus', 73, 'Aepyceros mylampus', 0, 6),
       ('posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat', 96, 'Cervus duvauceli', 0, 95),
       ('mattis odio donec vitae', 93, 'Cyrtodactylus louisiadensis', 0, 85),
       ('in libero ut massa volutpat convallis morbi odio odio', 80, 'Pitangus sulphuratus', 2, 28),
       ('ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', 11, 'Callipepla gambelii', 0, 97),
       ('porttitor id consequat in consequat ut nulla sed', 78, 'Zonotrichia capensis', 1, 38),
       ('pretium quis lectus', 15, 'Nannopterum harrisi', 2, 68),
       ('et ultrices posuere cubilia curae nulla', 15, 'Coracias caudata', 2, 24),
       ('aliquet maecenas leo', 75, 'Cebus albifrons', 2, 10),
       ('vivamus tortor duis mattis egestas metus', 1, 'Phascogale tapoatafa', 1, 23),
       ('eget elit sodales scelerisque mauris sit amet eros suspendisse', 96, 'Francolinus coqui', 1, 44),
       ('quam pharetra magna ac consequat metus sapien ut', 7, 'Macropus eugenii', 0, 36),
       ('sapien ut nunc', 83, 'Boa caninus', 0, 90),
       ('tortor duis mattis egestas metus', 93, 'Mirounga leonina', 1, 72),
       ('elementum eu interdum eu tincidunt', 98, 'Ara ararauna', 0, 42),
       ('amet sapien', 93, 'Ictalurus furcatus', 2, 45),
       ('rhoncus sed vestibulum', 49, 'Chlidonias leucopterus', 0, 61),
       ('maecenas tincidunt lacus at velit vivamus', 37, 'Ardea golieth', 0, 56),
       ('sapien urna pretium nisl ut volutpat sapien arcu sed augue', 23, 'Zosterops pallidus', 0, 48),
       ('nulla ultrices aliquet maecenas leo odio condimentum', 44, 'Rhea americana', 1, 84),
       ('sit amet consectetuer adipiscing elit', 93, 'Fregata magnificans', 0, 94),
       ('ac nibh fusce lacus purus aliquet at feugiat non pretium', 98, 'Mazama gouazoubira', 0, 47),
       ('nulla sed vel enim sit amet nunc', 70, 'Felis concolor', 0, 30),
       ('sociis natoque penatibus et magnis dis parturient montes nascetur', 50, 'Pseudocheirus peregrinus', 2, 54),
       ('in eleifend quam a odio in hac habitasse platea', 28, 'Eunectes sp.', 1, 33),
       ('aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 55, 'Antilope cervicapra', 1, 32),
       ('in porttitor pede', 41, 'Oryx gazella callotis', 2, 100),
       ('massa quis', 40, 'Spizaetus coronatus', 1, 30),
       ('in magna bibendum imperdiet nullam', 52, 'Taxidea taxus', 0, 22),
       ('nam congue risus', 28, 'Loris tardigratus', 2, 16),
       ('porttitor id consequat', 77, 'Hymenolaimus malacorhynchus', 1, 78),
       ('purus aliquet at feugiat non', 100, 'Ovibos moschatus', 0, 27),
       ('accumsan odio curabitur', 39, 'Certotrichas paena', 1, 4),
       ('velit eu est congue elementum in hac', 62, 'Meles meles', 0, 9),
       ('eros elementum pellentesque quisque porta', 21, 'Sagittarius serpentarius', 0, 42),
       ('vehicula consequat morbi a ipsum integer a nibh in quis', 34, 'Equus burchelli', 1, 10),
       ('mauris laoreet ut', 2, 'Anastomus oscitans', 2, 55),
       ('ut rhoncus', 52, 'Rhea americana', 1, 27),
       ('magna bibendum imperdiet nullam orci', 54, 'Orcinus orca', 1, 3),
       ('magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 78, 'Capreolus capreolus', 0,
        54),
       ('donec ut', 43, 'Uraeginthus granatina', 1, 87),
       ('non velit nec', 99, 'Tenrec ecaudatus', 0, 11),
       ('dictumst etiam faucibus cursus', 100, 'Meleagris gallopavo', 2, 26),
       ('luctus ultricies eu nibh quisque id justo sit amet sapien', 54, 'Limosa haemastica', 1, 20),
       ('felis eu sapien cursus vestibulum proin eu mi nulla', 14, 'Acinynox jubatus', 2, 5),
       ('sapien cum sociis natoque penatibus', 51, 'Deroptyus accipitrinus', 1, 47),
       ('vestibulum sagittis sapien cum', 16, 'Phoca vitulina', 1, 61),
       ('lobortis sapien sapien non mi', 27, 'Equus burchelli', 2, 49),
       ('erat quisque erat eros viverra eget', 73, 'Anser caerulescens', 2, 94),
       ('justo in blandit ultrices', 79, 'Phalacrocorax carbo', 0, 99),
       ('mauris vulputate elementum nullam', 19, 'Tamandua tetradactyla', 0, 2),
       ('augue vel accumsan tellus nisi eu orci mauris', 74, 'Pelecanus conspicillatus', 2, 74),
       ('justo eu massa donec', 70, 'Pteronura brasiliensis', 1, 58),
       ('sed nisl nunc rhoncus', 46, 'Lama glama', 2, 28),
       ('amet erat nulla tempus', 33, 'Nesomimus trifasciatus', 1, 18),
       ('in blandit ultrices enim lorem ipsum dolor', 50, 'Psophia viridis', 0, 19),
       ('mi sit amet lobortis sapien sapien', 42, 'Larus dominicanus', 1, 59),
       ('habitasse platea dictumst etiam faucibus cursus urna ut tellus', 63, 'Nyctea scandiaca', 2, 80),
       ('ultrices aliquet maecenas leo odio', 8, 'Sciurus vulgaris', 0, 59),
       ('ultrices posuere cubilia curae donec pharetra', 96, 'Bugeranus caruncalatus', 1, 98),
       ('primis in', 12, 'Papio cynocephalus', 0, 74),
       ('posuere metus vitae ipsum aliquam', 90, 'Ardea cinerea', 0, 89),
       ('aliquam lacus morbi quis tortor id nulla ultrices', 7, 'Irania gutteralis', 1, 75),
       ('fusce lacus purus', 80, 'Crotaphytus collaris', 1, 84),
       ('vulputate vitae nisl aenean lectus pellentesque eget', 67, 'Cercopithecus aethiops', 0, 56),
       ('rhoncus sed vestibulum sit amet cursus', 28, 'Vombatus ursinus', 1, 6),
       ('consequat in consequat ut nulla sed', 44, 'Felis concolor', 0, 93),
       ('velit id pretium', 9, 'Thylogale stigmatica', 0, 65),
       ('sit amet diam', 47, 'Stenella coeruleoalba', 0, 32),
       ('pede ullamcorper augue a suscipit', 51, 'Tamiasciurus hudsonicus', 1, 10),
       ('odio in hac habitasse platea dictumst maecenas ut', 21, 'Felis rufus', 2, 14),
       ('tempus semper est quam pharetra magna ac consequat', 31, 'Felis pardalis', 1, 42),
       ('molestie nibh in lectus pellentesque at', 53, 'Felis concolor', 1, 60),
       ('purus phasellus', 69, 'Lasiorhinus latifrons', 2, 81),
       ('luctus rutrum nulla tellus in', 52, 'Eurocephalus anguitimens', 0, 3),
       ('tempus vivamus in felis eu sapien cursus vestibulum proin', 4, 'Phalaropus lobatus', 0, 19),
       ('in est risus auctor sed tristique in tempus', 24, 'Phasianus colchicus', 2, 82),
       ('sed magna at', 60, 'Hippotragus niger', 0, 21),
       ('hac habitasse platea dictumst morbi vestibulum velit', 8, 'Macropus eugenii', 1, 7),
       ('tincidunt eget tempus vel pede', 22, 'unavailable', 0, 6),
       ('vel accumsan tellus nisi eu orci mauris lacinia sapien', 7, 'Phalacrocorax carbo', 1, 38),
       ('suspendisse potenti nullam porttitor', 56, 'Neophoca cinerea', 2, 56),
       ('sodales sed tincidunt eu felis fusce posuere felis sed', 71, 'Notechis semmiannulatus', 1, 81),
       ('ultrices posuere cubilia curae nulla dapibus dolor', 89, 'Phalacrocorax albiventer', 2, 97),
       ('nulla pede ullamcorper augue a suscipit nulla elit ac nulla', 13, 'Morelia spilotes variegata', 1, 17),
       ('tempus vivamus in felis eu sapien cursus', 50, 'Otaria flavescens', 2, 53),
       ('dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien', 73,
        'Felis silvestris lybica', 2, 62),
       ('in leo maecenas pulvinar lobortis est phasellus', 35, 'Manouria emys', 1, 97),
       ('ipsum primis in faucibus orci luctus et ultrices posuere', 96, 'Dusicyon thous', 0, 16),
       ('auctor sed tristique in tempus sit amet', 97, 'Chlidonias leucopterus', 1, 71),
       ('cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam', 39, 'Connochaetus taurinus', 0, 28),
       ('ipsum ac tellus semper interdum mauris', 37, 'Mycteria leucocephala', 2, 48),
       ('orci pede venenatis non sodales', 77, 'Geospiza sp.', 2, 4),
       ('elementum eu', 97, 'Ictonyx striatus', 2, 18),
       ('diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', 9, 'Sula dactylatra', 2, 68),
       ('magnis dis parturient montes', 41, 'Manouria emys', 1, 65),
       ('quis tortor id nulla ultrices', 72, 'Buteo jamaicensis', 0, 65),
       ('diam neque vestibulum eget vulputate ut ultrices vel augue', 49, 'Mustela nigripes', 2, 81),
       ('mattis pulvinar nulla pede ullamcorper augue a', 13, 'Centrocercus urophasianus', 1, 67),
       ('nulla justo aliquam quis turpis eget', 37, 'Elephas maximus bengalensis', 1, 62),
       ('porta volutpat erat', 98, 'Actophilornis africanus', 2, 92),
       ('lorem id ligula', 54, 'Gyps bengalensis', 0, 58),
       ('magna at nunc commodo placerat praesent', 19, 'Anas bahamensis', 1, 31),
       ('leo odio porttitor id consequat in', 25, 'Nucifraga columbiana', 2, 12),
       ('sed magna at nunc commodo placerat', 56, 'Lepilemur rufescens', 2, 51),
       ('dis parturient', 65, 'Tyto novaehollandiae', 1, 54),
       ('congue risus', 96, 'Carduelis pinus', 1, 63),
       ('eget tempus vel pede morbi porttitor', 46, 'Ovis canadensis', 1, 60),
       ('dignissim vestibulum vestibulum ante ipsum primis in faucibus', 20, 'Eurocephalus anguitimens', 0, 24),
       ('pede justo lacinia eget tincidunt eget tempus vel pede morbi', 63, 'Trichosurus vulpecula', 0, 17),
       ('in libero ut massa volutpat convallis morbi', 94, 'Herpestes javanicus', 0, 67),
       ('et ultrices posuere cubilia curae duis faucibus accumsan odio', 15, 'Ara ararauna', 2, 83),
       ('nunc commodo placerat praesent blandit nam nulla integer pede', 54, 'Coendou prehensilis', 2, 96),
       ('sed lacus morbi sem', 21, 'Papio ursinus', 1, 82),
       ('eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', 46, 'Spermophilus parryii', 2, 26),
       ('odio condimentum id luctus nec molestie sed', 12, 'Nectarinia chalybea', 1, 91),
       ('est donec odio justo', 7, 'Oreamnos americanus', 1, 24),
       ('at turpis a pede posuere nonummy integer non velit donec', 4, 'Mellivora capensis', 2, 40),
       ('eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 56, 'Macropus rufus', 1, 90),
       ('purus phasellus in felis donec semper', 70, 'Anastomus oscitans', 1, 88),
       ('turpis nec euismod', 75, 'Macropus agilis', 2, 36),
       ('est et tempus semper est quam pharetra magna', 3, 'Tragelaphus strepsiceros', 2, 3),
       ('massa id nisl venenatis lacinia aenean sit amet', 48, 'Bucephala clangula', 0, 91),
       ('proin risus praesent lectus', 76, 'Boa constrictor mexicana', 0, 23),
       ('libero nam dui proin leo odio porttitor', 8, 'Catharacta skua', 2, 8),
       ('sapien dignissim vestibulum vestibulum', 41, 'Mirounga leonina', 2, 42),
       ('orci luctus et ultrices', 45, 'Philetairus socius', 1, 99),
       ('augue aliquam erat volutpat in congue etiam justo', 93, 'Corallus hortulanus cooki', 2, 49),
       ('nulla dapibus dolor vel', 97, 'Phascogale tapoatafa', 1, 74),
       ('vel accumsan tellus', 21, 'Varanus komodensis', 1, 38),
       ('fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet', 59, 'Phalaropus fulicarius', 1, 33),
       ('dis parturient montes nascetur ridiculus mus vivamus', 10, 'Semnopithecus entellus', 0, 49),
       ('lectus pellentesque at nulla suspendisse potenti cras', 8, 'Loxodonta africana', 2, 76),
       ('pede ac', 36, 'Climacteris melanura', 2, 81),
       ('accumsan felis ut', 98, 'Centrocercus urophasianus', 1, 59),
       ('lacus at velit vivamus vel nulla eget eros elementum pellentesque', 2, 'Tayassu pecari', 1, 61),
       ('nunc commodo placerat praesent blandit nam nulla integer', 43, 'Manouria emys', 2, 56),
       ('vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 74, 'Milvago chimachima', 2, 89),
       ('elementum nullam varius nulla facilisi cras non', 31, 'Oncorhynchus nerka', 0, 97),
       ('ut volutpat sapien arcu sed augue aliquam', 9, 'Meleagris gallopavo', 2, 33),
       ('volutpat erat quisque erat eros viverra eget congue eget', 7, 'Canis lupus lycaon', 2, 52),
       ('dolor sit', 81, 'Graspus graspus', 1, 44),
       ('convallis tortor risus dapibus augue vel accumsan tellus nisi', 26, 'Eumetopias jubatus', 0, 59),
       ('congue elementum', 28, 'Larus fuliginosus', 1, 68),
       ('ultrices posuere cubilia', 70, 'Platalea leucordia', 1, 48),
       ('a pede posuere nonummy integer non velit donec diam neque', 94, 'Kobus leche robertsi', 0, 68),
       ('amet nunc viverra', 58, 'Pterocles gutturalis', 2, 64),
       ('est donec odio', 58, 'Priodontes maximus', 1, 36),
       ('justo lacinia eget', 32, 'Dendrocitta vagabunda', 2, 22),
       ('posuere cubilia curae duis faucibus accumsan odio curabitur convallis', 50, 'Martes americana', 0, 46),
       ('vivamus metus arcu adipiscing molestie', 5, 'Ardea golieth', 2, 11),
       ('rutrum ac lobortis vel dapibus at', 46, 'Zenaida asiatica', 1, 92),
       ('ac est lacinia nisi venenatis tristique fusce congue diam', 28, 'Libellula quadrimaculata', 2, 59),
       ('in faucibus orci luctus et ultrices posuere cubilia', 68, 'Eolophus roseicapillus', 1, 89),
       ('tempus vel pede morbi', 90, 'Varanus sp.', 2, 69),
       ('viverra dapibus', 91, 'Perameles nasuta', 1, 51),
       ('et ultrices', 68, 'Rhea americana', 1, 32),
       ('blandit mi', 7, 'Pycnonotus nigricans', 0, 23),
       ('a pede posuere nonummy integer non velit', 21, 'Giraffe camelopardalis', 0, 34),
       ('orci mauris lacinia sapien quis libero nullam sit amet', 57, 'Psophia viridis', 0, 35),
       ('auctor sed tristique in tempus sit amet sem fusce', 26, 'Phoenicopterus ruber', 2, 51),
       ('eget congue eget semper rutrum nulla nunc purus phasellus in', 53, 'Eremophila alpestris', 0, 81),
       ('cursus vestibulum proin eu mi nulla ac enim in tempor', 4, 'Choloepus hoffmani', 1, 69),
       ('vivamus metus arcu adipiscing molestie hendrerit', 24, 'unavailable', 2, 1),
       ('magna ac consequat', 25, 'Psophia viridis', 2, 33),
       ('venenatis turpis enim blandit mi in porttitor pede justo eu', 36, 'Cygnus buccinator', 0, 74),
       ('sollicitudin mi sit amet lobortis sapien sapien non mi integer', 77, 'Mazama gouazoubira', 0, 9),
       ('praesent id massa id nisl venenatis lacinia aenean sit amet', 6, 'Microcebus murinus', 2, 83),
       ('augue vestibulum ante', 84, 'Podargus strigoides', 2, 6),
       ('ipsum dolor', 76, 'Antilocapra americana', 1, 63),
       ('viverra dapibus nulla', 72, 'Papio ursinus', 0, 18),
       ('elit proin interdum mauris non', 16, 'Cervus duvauceli', 1, 54),
       ('amet sapien dignissim vestibulum vestibulum ante ipsum', 20, 'Felis chaus', 1, 19),
       ('sem fusce consequat nulla', 89, 'Ciconia ciconia', 1, 35),
       ('mauris non ligula pellentesque ultrices phasellus id sapien', 50, 'Grus rubicundus', 1, 35),
       ('aenean sit', 17, 'Ephippiorhynchus mycteria', 2, 51),
       ('pharetra magna ac', 44, 'Tyto novaehollandiae', 2, 98),
       ('feugiat non pretium', 83, 'Lycaon pictus', 2, 53),
       ('consectetuer adipiscing elit proin interdum mauris', 91, 'Ictonyx striatus', 0, 52),
       ('varius nulla facilisi cras non velit nec nisi', 49, 'Alligator mississippiensis', 0, 39),
       ('sagittis dui vel nisl duis ac', 17, 'Colaptes campestroides', 0, 11),
       ('dictumst etiam faucibus cursus urna ut tellus nulla ut', 37, 'Dicrurus adsimilis', 1, 76),
       ('libero ut massa volutpat convallis morbi odio odio elementum', 66, 'Isoodon obesulus', 2, 65),
       ('turpis enim blandit mi in porttitor', 12, 'Microcavia australis', 0, 77),
       ('ultrices enim lorem ipsum dolor sit amet consectetuer', 41, 'Vanellus armatus', 2, 31),
       ('ante ipsum primis in faucibus orci', 11, 'Ammospermophilus nelsoni', 2, 68),
       ('risus semper porta volutpat quam pede lobortis ligula sit', 70, 'Plegadis falcinellus', 1, 80),
       ('nunc vestibulum ante ipsum', 49, 'Oreamnos americanus', 2, 44),
       ('sed vestibulum sit amet cursus id turpis integer', 52, 'Antilope cervicapra', 1, 96),
       ('vitae nisi nam ultrices libero non mattis', 21, 'Ephippiorhynchus mycteria', 0, 34),
       ('nunc nisl', 76, 'Sylvicapra grimma', 0, 56),
       ('lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', 91, 'Porphyrio porphyrio', 2, 10),
       ('luctus ultricies eu nibh quisque id justo sit amet sapien', 14, 'Eudromia elegans', 0, 76),
       ('turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 46, 'Diomedea irrorata', 2, 85),
       ('ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 63, 'Ammospermophilus nelsoni', 0, 15),
       ('sem sed sagittis nam congue', 25, 'Butorides striatus', 1, 80),
       ('leo odio porttitor id consequat in consequat ut', 71, 'Paraxerus cepapi', 2, 14),
       ('amet cursus id', 38, 'Leprocaulinus vipera', 1, 44),
       ('convallis morbi odio odio elementum', 47, 'Potorous tridactylus', 0, 16),
       ('nulla justo aliquam quis', 7, 'Aonyx cinerea', 1, 80),
       ('odio cras mi pede malesuada in', 57, 'Psittacula krameri', 2, 65),
       ('eget eleifend luctus ultricies eu', 53, 'Spermophilus richardsonii', 2, 63),
       ('eget vulputate ut', 32, 'Paroaria gularis', 0, 45),
       ('magnis dis parturient montes nascetur ridiculus mus vivamus', 69, 'Pan troglodytes', 2, 14),
       ('cum sociis natoque', 74, 'Antilope cervicapra', 1, 22),
       ('nisl duis bibendum felis sed interdum venenatis turpis', 43, 'Acrantophis madagascariensis', 2, 30),
       ('nisl venenatis', 23, 'Phalaropus fulicarius', 2, 24),
       ('sollicitudin mi sit amet lobortis sapien sapien non mi integer', 19, 'Tayassu tajacu', 2, 25),
       ('sit amet', 71, 'unavailable', 0, 86),
       ('erat volutpat in congue', 92, 'Pteronura brasiliensis', 1, 87),
       ('ligula in lacus curabitur at ipsum ac tellus semper interdum', 64, 'Tamandua tetradactyla', 1, 7),
       ('quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum', 48, 'Uraeginthus angolensis', 1, 18),
       ('porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', 88, 'Bison bison', 2, 14),
       ('gravida sem praesent id massa', 76, 'Alopex lagopus', 1, 69),
       ('etiam justo etiam pretium', 67, 'Bubo virginianus', 1, 76),
       ('curabitur gravida nisi at nibh', 45, 'Anastomus oscitans', 1, 33),
       ('semper sapien a libero', 67, 'Phalacrocorax carbo', 1, 35),
       ('at velit vivamus vel nulla eget eros elementum pellentesque', 48, 'Coendou prehensilis', 2, 90),
       ('pretium iaculis diam erat fermentum justo nec', 67, 'Felis chaus', 0, 42),
       ('platea dictumst morbi', 40, 'Taurotagus oryx', 1, 15),
       ('vehicula condimentum curabitur in libero ut massa volutpat', 72, 'Nasua nasua', 0, 12),
       ('in porttitor pede justo', 8, 'Bugeranus caruncalatus', 1, 67),
       ('amet erat nulla', 39, 'Stercorarius longicausus', 0, 84),
       ('sapien in sapien iaculis congue vivamus metus arcu', 23, 'Sceloporus magister', 0, 24),
       ('montes nascetur ridiculus mus etiam vel', 100, 'Eudromia elegans', 1, 32),
       ('quisque erat eros viverra eget', 55, 'Phalaropus lobatus', 2, 42),
       ('est et tempus semper est quam pharetra magna ac', 45, 'Naja sp.', 2, 4),
       ('magna ac consequat metus sapien ut nunc vestibulum ante ipsum', 52, 'Tachyglossus aculeatus', 1, 29),
       ('eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', 88, 'Erethizon dorsatum', 1, 8),
       ('duis mattis egestas', 93, 'Microcebus murinus', 1, 14),
       ('sem mauris laoreet ut rhoncus aliquet pulvinar sed', 7, 'Macropus fuliginosus', 1, 32),
       ('orci luctus et ultrices', 83, 'Myrmecophaga tridactyla', 2, 44),
       ('at velit', 48, 'Pterocles gutturalis', 2, 11),
       ('ligula suspendisse ornare consequat lectus', 6, 'Seiurus aurocapillus', 0, 52),
       ('sed ante vivamus tortor duis', 37, 'Creagrus furcatus', 0, 45),
       ('aenean lectus pellentesque eget nunc donec quis', 97, 'Bassariscus astutus', 0, 55),
       ('lacinia aenean', 54, 'Lycaon pictus', 0, 99),
       ('vel ipsum', 77, 'Bettongia penicillata', 2, 43),
       ('elit proin risus praesent', 60, 'Paroaria gularis', 1, 74),
       ('turpis integer aliquet massa id lobortis convallis tortor risus dapibus', 55, 'Cordylus giganteus', 1, 80),
       ('vel augue vestibulum rutrum rutrum neque aenean', 53, 'Ninox superciliaris', 0, 67),
       ('donec semper sapien a libero', 24, 'Uraeginthus granatina', 0, 59),
       ('in felis donec semper sapien', 99, 'Crotalus adamanteus', 2, 23),
       ('vulputate luctus cum sociis natoque', 70, 'Larus fuliginosus', 2, 7),
       ('duis bibendum', 69, 'Mazama americana', 1, 81),
       ('diam id ornare imperdiet sapien urna pretium nisl', 21, 'Spermophilus armatus', 2, 31),
       ('consequat dui nec nisi volutpat', 72, 'Loxodonta africana', 0, 53),
       ('non quam nec', 46, 'Ciconia episcopus', 1, 2),
       ('eget orci vehicula condimentum', 25, 'Ardea cinerea', 2, 19),
       ('rutrum neque aenean auctor', 72, 'Centrocercus urophasianus', 2, 11),
       ('rhoncus aliquam lacus morbi quis tortor id nulla', 45, 'Bubalornis niger', 0, 48),
       ('ante ipsum primis in faucibus', 40, 'Canis aureus', 2, 57),
       ('ante ipsum primis in faucibus orci luctus', 62, 'Meles meles', 2, 61),
       ('semper sapien a', 25, 'Sceloporus magister', 1, 14),
       ('feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', 54, 'Porphyrio porphyrio', 2, 79),
       ('potenti nullam porttitor lacus at turpis donec', 56, 'Gabianus pacificus', 0, 96),
       ('eros vestibulum', 67, 'unavailable', 0, 36),
       ('eu orci mauris lacinia sapien', 73, 'Dicrostonyx groenlandicus', 1, 84),
       ('tellus nulla ut erat id mauris vulputate elementum', 99, 'Neophron percnopterus', 0, 71),
       ('laoreet ut', 96, 'Grus rubicundus', 1, 63),
       ('vivamus vel nulla', 55, 'Gabianus pacificus', 1, 36),
       ('ultrices libero non mattis pulvinar nulla', 73, 'Otaria flavescens', 1, 18),
       ('congue diam id ornare imperdiet', 91, 'Psophia viridis', 1, 35),
       ('nec sem duis', 2, 'Trichosurus vulpecula', 0, 90),
       ('convallis eget eleifend luctus ultricies', 42, 'Haematopus ater', 0, 11),
       ('nulla dapibus dolor vel est donec odio justo sollicitudin ut', 32, 'Cereopsis novaehollandiae', 1, 100),
       ('praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 67, 'Casmerodius albus', 2, 35),
       ('donec semper sapien a libero', 19, 'Panthera tigris', 2, 63),
       ('proin leo odio porttitor', 31, 'Zenaida galapagoensis', 0, 19),
       ('at nulla suspendisse', 4, 'Spheniscus mendiculus', 0, 58),
       ('ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', 38, 'Procyon lotor', 1, 44),
       ('dapibus duis at velit eu est', 95, 'Macropus rufogriseus', 1, 21),
       ('nibh quisque', 78, 'Spheniscus mendiculus', 2, 72),
       ('mauris viverra diam vitae quam suspendisse', 11, 'Carduelis pinus', 0, 6),
       ('volutpat convallis', 6, 'Geochelone elephantopus', 2, 52),
       ('interdum mauris ullamcorper purus sit amet nulla quisque arcu libero', 61, 'Kobus vardonii vardoni', 2, 4),
       ('morbi non lectus aliquam sit amet diam in magna', 40, 'Ovis dalli stonei', 2, 37),
       ('bibendum imperdiet nullam orci', 91, 'Spermophilus parryii', 1, 67),
       ('nisl nunc', 5, 'Isoodon obesulus', 2, 7),
       ('vel nulla eget eros elementum pellentesque quisque porta volutpat erat', 34, 'Lamprotornis nitens', 0, 36),
       ('massa donec dapibus duis at velit eu est', 3, 'Megaderma spasma', 2, 34),
       ('dolor sit amet', 66, 'Ninox superciliaris', 1, 83),
       ('in faucibus orci luctus et', 84, 'Ciconia ciconia', 2, 89),
       ('amet diam in magna bibendum', 50, 'Heloderma horridum', 1, 60),
       ('aenean auctor gravida', 26, 'Ctenophorus ornatus', 2, 73),
       ('mauris ullamcorper purus sit amet nulla quisque', 28, 'Pytilia melba', 2, 14),
       ('quisque porta volutpat erat quisque', 94, 'Zalophus californicus', 1, 6),
       ('magna bibendum imperdiet nullam orci pede venenatis non sodales sed', 14, 'Nectarinia chalybea', 2, 55),
       ('turpis a pede posuere', 17, 'Chamaelo sp.', 2, 95),
       ('eget eleifend luctus ultricies', 41, 'Bugeranus caruncalatus', 2, 78),
       ('venenatis turpis', 93, 'Canis aureus', 1, 67),
       ('faucibus orci luctus et ultrices', 27, 'Oxybelis fulgidus', 0, 43),
       ('curae mauris viverra diam vitae quam suspendisse potenti', 46, 'Bassariscus astutus', 0, 31),
       ('dapibus augue vel accumsan tellus', 47, 'Mycteria ibis', 0, 69),
       ('proin risus praesent lectus', 17, 'Alopex lagopus', 1, 23),
       ('etiam vel augue vestibulum', 80, 'unavailable', 1, 46),
       ('ac lobortis vel dapibus at diam nam', 17, 'Limosa haemastica', 1, 33),
       ('libero nam dui proin leo', 69, 'Parus atricapillus', 0, 91),
       ('orci eget', 59, 'Sylvicapra grimma', 0, 20),
       ('sit amet nunc viverra dapibus nulla suscipit ligula in', 100, 'Paraxerus cepapi', 0, 81),
       ('congue elementum in', 17, 'Coluber constrictor', 1, 20),
       ('ultrices posuere cubilia curae donec', 6, 'Colaptes campestroides', 0, 92),
       ('orci nullam molestie nibh in lectus pellentesque at nulla suspendisse', 20, 'Boa constrictor mexicana', 0, 65),
       ('pulvinar nulla pede ullamcorper augue a suscipit', 16, 'Zenaida galapagoensis', 1, 87),
       ('nunc donec', 45, 'Vanessa indica', 1, 15),
       ('primis in faucibus orci', 37, 'unavailable', 1, 15),
       ('quam turpis adipiscing lorem vitae mattis nibh', 55, 'Nectarinia chalybea', 0, 48),
       ('dapibus at diam', 43, 'Naja haje', 2, 49),
       ('sollicitudin mi sit amet lobortis sapien sapien non mi integer', 20, 'Potos flavus', 0, 40),
       ('interdum mauris ullamcorper purus sit amet nulla quisque', 54, 'Alopochen aegyptiacus', 2, 44),
       ('id pretium', 54, 'Anas punctata', 2, 79),
       ('penatibus et magnis dis parturient montes nascetur ridiculus mus', 24, 'Columba livia', 1, 11),
       ('sodales sed tincidunt', 41, 'Dusicyon thous', 1, 33),
       ('odio porttitor id consequat in consequat ut nulla sed accumsan', 87, 'Lycosa godeffroyi', 2, 100),
       ('lobortis est phasellus sit amet', 83, 'Limnocorax flavirostra', 1, 9),
       ('id lobortis convallis tortor', 9, 'Anthropoides paradisea', 2, 51),
       ('non lectus aliquam', 5, 'Epicrates cenchria maurus', 0, 69),
       ('sed augue aliquam erat volutpat', 61, 'Ovibos moschatus', 2, 86),
       ('tortor eu pede', 68, 'Pseudocheirus peregrinus', 1, 81),
       ('hac habitasse platea dictumst', 54, 'Giraffe camelopardalis', 2, 37),
       ('placerat praesent blandit nam nulla integer pede justo lacinia', 16, 'Heloderma horridum', 2, 26),
       ('mus vivamus vestibulum sagittis', 45, 'Choriotis kori', 1, 82),
       ('porta volutpat erat quisque erat eros viverra eget congue', 11, 'Bos taurus', 2, 17),
       ('justo maecenas', 79, 'Felis serval', 0, 70),
       ('rhoncus aliquet pulvinar sed nisl nunc', 85, 'Motacilla aguimp', 2, 47),
       ('mauris laoreet ut rhoncus aliquet pulvinar sed', 79, 'Macropus eugenii', 1, 15),
       ('fusce consequat nulla nisl nunc nisl duis bibendum', 31, 'Stercorarius longicausus', 1, 17),
       ('blandit nam nulla integer pede justo', 60, 'Sarcorhamphus papa', 1, 79),
       ('pede libero', 58, 'Lycaon pictus', 1, 38),
       ('eu massa donec', 18, 'Damaliscus lunatus', 1, 43),
       ('erat id', 27, 'Phaethon aethereus', 0, 98),
       ('iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate', 4, 'Dicrostonyx groenlandicus',
        0, 55),
       ('id lobortis convallis tortor risus dapibus augue vel accumsan tellus', 63, 'Bassariscus astutus', 2, 77),
       ('cubilia curae mauris', 91, 'Eubalaena australis', 0, 27),
       ('eget tincidunt eget tempus vel pede', 29, 'Haematopus ater', 0, 4),
       ('luctus tincidunt nulla mollis molestie lorem quisque', 27, 'Psophia viridis', 1, 27),
       ('ut erat', 14, 'Canis aureus', 2, 73),
       ('metus vitae', 76, 'Lamprotornis nitens', 0, 24),
       ('posuere nonummy integer', 20, 'Cordylus giganteus', 1, 36),
       ('sapien placerat', 31, 'Laniarius ferrugineus', 0, 65),
       ('justo sollicitudin ut suscipit a feugiat et eros vestibulum', 48, 'Naja nivea', 2, 49),
       ('lacus curabitur at ipsum', 9, 'Rhea americana', 2, 67),
       ('eu tincidunt in leo', 82, 'Tiliqua scincoides', 1, 13),
       ('sed justo', 73, 'Bos mutus', 0, 63),
       ('consectetuer adipiscing elit proin risus', 99, 'Thylogale stigmatica', 0, 10),
       ('nulla suscipit ligula in lacus curabitur', 77, 'Grus canadensis', 2, 9),
       ('semper est', 38, 'Hyaena brunnea', 2, 56),
       ('tristique est et tempus semper est quam pharetra', 84, 'Butorides striatus', 1, 72),
       ('dolor sit amet consectetuer adipiscing elit proin risus', 68, 'Epicrates cenchria maurus', 1, 27),
       ('at nunc commodo placerat praesent blandit nam nulla integer', 90, 'Climacteris melanura', 1, 75),
       ('purus sit amet', 65, 'Vulpes chama', 2, 31),
       ('penatibus et magnis dis parturient montes', 80, 'Sciurus vulgaris', 0, 72),
       ('viverra diam vitae quam', 57, 'Eumetopias jubatus', 1, 82),
       ('dapibus dolor vel est donec odio justo sollicitudin ut', 12, 'Pitangus sulphuratus', 2, 99),
       ('dui luctus rutrum nulla tellus in sagittis dui vel', 55, 'Oncorhynchus nerka', 0, 10),
       ('commodo placerat praesent blandit nam nulla integer pede justo', 49, 'Laniaurius atrococcineus', 2, 94),
       ('congue vivamus', 92, 'Cygnus buccinator', 2, 38),
       ('sit amet erat nulla tempus vivamus in felis eu', 90, 'Boa constrictor mexicana', 0, 16),
       ('luctus cum sociis natoque penatibus et magnis', 29, 'Antechinus flavipes', 2, 34),
       ('nulla ultrices aliquet maecenas leo odio', 27, 'Leprocaulinus vipera', 1, 57),
       ('accumsan tellus nisi eu orci mauris lacinia sapien quis', 31, 'Heloderma horridum', 2, 22),
       ('elit proin risus praesent lectus vestibulum quam sapien', 2, 'Melanerpes erythrocephalus', 1, 52),
       ('urna ut tellus nulla ut erat id mauris vulputate', 58, 'Eutamias minimus', 0, 72),
       ('faucibus orci luctus et ultrices posuere', 25, 'Ovis canadensis', 1, 90),
       ('vulputate elementum nullam varius nulla facilisi cras non velit nec', 26, 'Spizaetus coronatus', 0, 94),
       ('consequat morbi a ipsum integer', 36, 'Coluber constrictor', 1, 92),
       ('tempus sit', 31, 'Alces alces', 1, 55),
       ('fermentum justo nec condimentum neque sapien placerat', 4, 'Phalacrocorax niger', 1, 65),
       ('feugiat et eros vestibulum ac est lacinia nisi', 89, 'Pandon haliaetus', 0, 11),
       ('primis in faucibus orci', 38, 'Motacilla aguimp', 0, 96),
       ('morbi vestibulum velit id pretium iaculis diam erat', 48, 'Bassariscus astutus', 2, 14),
       ('ac consequat metus sapien ut nunc', 99, 'Corythornis cristata', 0, 57),
       ('sit amet', 76, 'Galago crassicaudataus', 2, 32),
       ('fermentum justo nec condimentum neque sapien', 70, 'Helogale undulata', 1, 89),
       ('in est risus auctor sed', 86, 'Dicrostonyx groenlandicus', 2, 93),
       ('suspendisse ornare consequat lectus in est risus auctor sed tristique', 45, 'Cacatua tenuirostris', 0, 20),
       ('in faucibus orci', 43, 'Canis lupus lycaon', 0, 34),
       ('leo maecenas', 36, 'Anathana ellioti', 0, 87),
       ('pulvinar lobortis est phasellus sit amet erat nulla', 49, 'Eubalaena australis', 1, 25),
       ('eget congue', 13, 'Charadrius tricollaris', 2, 61),
       ('aliquam erat volutpat in congue etiam justo etiam pretium iaculis', 91, 'Eumetopias jubatus', 2, 14),
       ('sed magna at nunc commodo placerat', 77, 'Charadrius tricollaris', 0, 12),
       ('sagittis sapien cum', 28, 'Columba livia', 2, 87),
       ('volutpat erat quisque erat eros viverra eget congue eget semper', 30, 'Canis aureus', 1, 64),
       ('nunc vestibulum ante ipsum primis in faucibus', 96, 'Ateles paniscus', 2, 37),
       ('ultrices phasellus id sapien', 1, 'Agouti paca', 1, 62),
       ('pellentesque ultrices', 87, 'Picoides pubescens', 1, 43),
       ('tincidunt eget tempus vel pede morbi', 74, 'Larus novaehollandiae', 1, 28),
       ('amet sapien dignissim', 18, 'Varanus salvator', 2, 44),
       ('parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 18, 'Dendrocygna viduata', 2, 5),
       ('nulla tempus vivamus', 81, 'Microcebus murinus', 2, 95),
       ('potenti cras in purus eu magna vulputate luctus', 52, 'Cercatetus concinnus', 0, 13),
       ('ipsum primis in faucibus orci luctus et ultrices posuere', 65, 'Boa caninus', 1, 71),
       ('in faucibus orci luctus et ultrices', 82, 'Alopochen aegyptiacus', 0, 76),
       ('justo nec condimentum neque sapien', 71, 'Philetairus socius', 1, 24),
       ('sit amet consectetuer adipiscing elit proin risus', 3, 'Buteo galapagoensis', 2, 73),
       ('primis in faucibus orci luctus et', 93, 'Pycnonotus barbatus', 2, 17),
       ('erat curabitur gravida nisi at nibh in hac', 66, 'Laniaurius atrococcineus', 0, 96),
       ('cubilia curae nulla dapibus dolor vel est donec odio justo', 28, 'Tockus flavirostris', 1, 15),
       ('odio donec vitae nisi nam ultrices libero non', 78, 'Alligator mississippiensis', 1, 56),
       ('platea dictumst etiam faucibus cursus urna', 33, 'Petaurus breviceps', 2, 61),
       ('consequat dui nec', 37, 'Cereopsis novaehollandiae', 2, 98),
       ('lobortis est', 55, 'Carduelis uropygialis', 0, 65),
       ('eros elementum', 82, 'Bassariscus astutus', 2, 16),
       ('eget rutrum at lorem integer tincidunt ante vel ipsum', 58, 'Papio ursinus', 1, 17),
       ('aliquet maecenas leo odio condimentum id luctus nec', 84, 'Eudyptula minor', 1, 86),
       ('lacus at turpis donec posuere metus vitae', 21, 'Felis serval', 0, 22),
       ('nunc purus phasellus in felis donec semper sapien', 53, 'Zosterops pallidus', 0, 93),
       ('lacus at', 39, 'Alopochen aegyptiacus', 2, 18),
       ('justo eu massa donec dapibus duis', 14, 'Nyctereutes procyonoides', 0, 13),
       ('nullam porttitor lacus at turpis donec posuere', 22, 'Corvus albicollis', 2, 2),
       ('magna vulputate luctus cum sociis', 89, 'Spheniscus mendiculus', 0, 94),
       ('augue aliquam erat volutpat in congue', 47, 'Hippotragus equinus', 2, 56),
       ('elementum ligula vehicula consequat morbi', 90, 'Lycosa godeffroyi', 2, 10),
       ('rhoncus aliquam lacus morbi quis tortor id nulla', 98, 'Zonotrichia capensis', 1, 23),
       ('donec quis orci eget orci vehicula condimentum curabitur', 60, 'Zosterops pallidus', 1, 59),
       ('pulvinar sed nisl', 38, 'Trichosurus vulpecula', 1, 22),
       ('quam turpis adipiscing', 63, 'Felis chaus', 2, 32),
       ('varius nulla facilisi cras non velit', 61, 'Drymarchon corias couperi', 1, 58),
       ('ipsum praesent blandit lacinia erat', 62, 'Uraeginthus granatina', 0, 50),
       ('nulla mollis molestie lorem quisque', 73, 'Ara chloroptera', 0, 31),
       ('aliquam lacus morbi quis tortor id nulla', 35, 'Dendrohyrax brucel', 1, 90),
       ('varius nulla facilisi cras', 44, 'Ursus americanus', 1, 32),
       ('nulla eget eros elementum pellentesque quisque porta volutpat erat quisque', 43, 'Cercatetus concinnus', 0, 2),
       ('ac leo pellentesque ultrices mattis odio donec vitae nisi nam', 76, 'Sagittarius serpentarius', 2, 12),
       ('lectus aliquam sit', 80, 'Colobus guerza', 0, 12),
       ('in est risus', 40, 'Callipepla gambelii', 0, 98),
       ('lorem ipsum dolor sit amet consectetuer adipiscing', 25, 'Ceryle rudis', 2, 2),
       ('in hac habitasse platea', 31, 'Anitibyx armatus', 1, 85),
       ('vel enim', 8, 'Bucephala clangula', 2, 46),
       ('pede malesuada in imperdiet et commodo vulputate justo', 100, 'Anastomus oscitans', 1, 80),
       ('ante vel ipsum praesent blandit lacinia erat vestibulum sed', 20, 'Ursus arctos', 0, 72),
       ('in hac habitasse platea dictumst morbi vestibulum velit id', 10, 'Porphyrio porphyrio', 2, 71),
       ('pede lobortis ligula sit amet eleifend pede libero', 79, 'Physignathus cocincinus', 0, 70),
       ('a libero nam dui proin leo odio porttitor', 17, 'Choriotis kori', 1, 61),
       ('in purus eu magna vulputate', 67, 'Felis serval', 1, 90),
       ('sit amet lobortis sapien sapien', 89, 'Bucephala clangula', 2, 45),
       ('viverra eget congue eget', 80, 'Procyon lotor', 2, 98),
       ('sollicitudin mi sit amet lobortis sapien', 60, 'Ramphastos tucanus', 2, 68),
       ('consequat varius', 36, 'Connochaetus taurinus', 0, 18),
       ('posuere nonummy integer', 36, 'Tamiasciurus hudsonicus', 2, 55),
       ('convallis duis consequat', 51, 'Bucorvus leadbeateri', 1, 30),
       ('justo maecenas rhoncus aliquam lacus morbi', 25, 'Pitangus sulphuratus', 0, 95),
       ('phasellus in', 52, 'Mephitis mephitis', 1, 14),
       ('eget nunc donec quis orci eget orci vehicula condimentum', 65, 'Spermophilus armatus', 2, 5),
       ('eu tincidunt in leo maecenas pulvinar', 35, 'Alopex lagopus', 2, 70),
       ('vestibulum ante ipsum primis in faucibus', 78, 'Vombatus ursinus', 0, 53),
       ('justo in blandit ultrices enim lorem ipsum', 95, 'Varanus komodensis', 1, 66),
       ('dapibus augue vel accumsan tellus nisi', 94, 'Vulpes chama', 1, 53),
       ('nascetur ridiculus mus', 30, 'Myrmecophaga tridactyla', 0, 85),
       ('suspendisse potenti in', 98, 'Terrapene carolina', 0, 6),
       ('sagittis nam congue', 20, 'Recurvirostra avosetta', 2, 75),
       ('ante ipsum', 96, 'Varanus sp.', 1, 49),
       ('pellentesque ultrices phasellus', 80, 'Tamiasciurus hudsonicus', 1, 10),
       ('eget semper rutrum nulla nunc purus', 64, 'Eremophila alpestris', 2, 1),
       ('dui maecenas tristique', 53, 'Castor canadensis', 0, 43),
       ('dictumst etiam faucibus cursus', 79, 'Heloderma horridum', 0, 46),
       ('aliquet ultrices erat tortor sollicitudin mi', 22, 'Acrantophis madagascariensis', 2, 16),
       ('nulla facilisi cras non velit nec nisi', 15, 'Carduelis pinus', 0, 68),
       ('diam erat fermentum justo', 29, 'Cacatua tenuirostris', 1, 91),
       ('sem mauris laoreet ut', 26, 'Graspus graspus', 2, 75),
       ('ultrices posuere cubilia curae nulla dapibus dolor vel est donec', 67, 'Phasianus colchicus', 0, 23),
       ('duis bibendum felis sed interdum venenatis turpis enim blandit', 79, 'Cervus elaphus', 0, 75),
       ('morbi vel lectus in quam fringilla rhoncus mauris enim leo', 42, 'Nyctea scandiaca', 1, 13),
       ('bibendum felis sed interdum venenatis turpis enim blandit mi', 65, 'Cacatua tenuirostris', 1, 54),
       ('varius nulla facilisi cras non velit nec', 26, 'unavailable', 2, 76),
       ('luctus cum sociis natoque penatibus et magnis dis parturient montes', 40, 'Bassariscus astutus', 0, 71),
       ('sapien arcu', 7, 'Acrantophis madagascariensis', 2, 20),
       ('eleifend pede libero quis orci nullam molestie nibh', 30, 'Anser anser', 2, 35),
       ('in ante vestibulum ante ipsum primis in faucibus', 46, 'Anitibyx armatus', 0, 26),
       ('luctus et ultrices posuere', 87, 'Propithecus verreauxi', 2, 92),
       ('in felis donec semper sapien a libero', 46, 'Sula nebouxii', 2, 30),
       ('vestibulum eget vulputate ut ultrices vel augue', 34, 'Larus novaehollandiae', 1, 62),
       ('ipsum integer', 68, 'Macropus giganteus', 2, 53),
       ('augue a suscipit nulla elit ac', 12, 'Giraffe camelopardalis', 0, 57),
       ('suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', 65, 'Tachyglossus aculeatus', 2, 11),
       ('pellentesque quisque porta volutpat erat quisque erat', 80, 'Raphicerus campestris', 2, 56),
       ('iaculis justo in', 22, 'Ardea golieth', 1, 79),
       ('consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien', 3, 'Bugeranus caruncalatus',
        0, 34),
       ('pulvinar lobortis', 70, 'Alligator mississippiensis', 0, 91),
       ('vitae consectetuer eget rutrum at lorem integer', 8, 'Varanus sp.', 0, 55),
       ('orci mauris lacinia sapien quis libero nullam sit', 8, 'Dendrocitta vagabunda', 1, 77),
       ('tortor risus dapibus augue vel accumsan tellus nisi eu orci', 78, 'Porphyrio porphyrio', 0, 12),
       ('lacus at turpis donec posuere', 19, 'Cacatua tenuirostris', 0, 35),
       ('non velit nec nisi vulputate', 29, 'Hystrix cristata', 2, 22),
       ('sit amet nunc viverra', 96, 'Loris tardigratus', 2, 87),
       ('vestibulum ante', 87, 'Crotalus cerastes', 0, 13),
       ('lacus purus aliquet at feugiat non pretium quis lectus', 70, 'Mabuya spilogaster', 1, 92),
       ('condimentum neque', 74, 'Toxostoma curvirostre', 2, 63),
       ('purus eu magna vulputate luctus cum sociis natoque', 92, 'Hystrix cristata', 1, 23),
       ('at vulputate', 28, 'Diceros bicornis', 1, 18),
       ('in blandit ultrices enim lorem', 15, 'Trichoglossus haematodus moluccanus', 1, 96),
       ('consequat ut nulla sed accumsan', 35, 'Eumetopias jubatus', 0, 8),
       ('sagittis sapien cum sociis natoque penatibus', 18, 'Crotalus adamanteus', 2, 52),
       ('quis turpis sed ante vivamus tortor duis mattis', 94, 'Myotis lucifugus', 1, 40),
       ('a suscipit nulla elit ac nulla', 75, 'Haliaeetus leucoryphus', 2, 93),
       ('pretium nisl ut volutpat sapien', 12, 'Vanessa indica', 0, 4),
       ('diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', 93, 'Mustela nigripes', 0, 50),
       ('egestas metus aenean fermentum donec ut mauris eget', 43, 'Damaliscus dorcas', 0, 1),
       ('vitae nisi nam ultrices libero non mattis pulvinar nulla', 71, 'Damaliscus dorcas', 0, 57),
       ('pulvinar lobortis', 70, 'Bucorvus leadbeateri', 2, 32),
       ('justo morbi ut odio cras mi pede malesuada', 32, 'Hyaena hyaena', 1, 33),
       ('arcu sed augue', 64, 'Macropus rufogriseus', 0, 52),
       ('ut rhoncus aliquet pulvinar sed nisl nunc', 91, 'Crocuta crocuta', 2, 57),
       ('elementum eu interdum eu tincidunt in', 53, 'Dacelo novaeguineae', 2, 10),
       ('non mattis', 58, 'Crotaphytus collaris', 1, 61),
       ('suspendisse potenti nullam porttitor', 41, 'Otaria flavescens', 0, 93),
       ('vitae nisi nam', 91, 'Ephippiorhynchus mycteria', 2, 21),
       ('suscipit ligula in lacus curabitur at ipsum', 42, 'Crocuta crocuta', 0, 31),
       ('ante ipsum primis', 9, 'Ramphastos tucanus', 1, 1),
       ('fermentum donec ut mauris eget massa tempor convallis nulla neque', 88, 'Ara ararauna', 0, 20),
       ('rhoncus aliquam', 49, 'Diomedea irrorata', 1, 36),
       ('lobortis sapien sapien non mi integer ac neque', 14, 'Pitangus sulphuratus', 1, 85),
       ('sem sed sagittis nam congue risus semper', 79, 'Columba livia', 0, 32),
       ('bibendum felis sed interdum', 50, 'Spheniscus magellanicus', 0, 15),
       ('semper interdum mauris', 38, 'Choriotis kori', 0, 26),
       ('praesent id massa', 24, 'Lama pacos', 2, 35),
       ('in leo maecenas pulvinar', 100, 'Felis caracal', 1, 94),
       ('nunc donec', 8, 'Felis silvestris lybica', 0, 9),
       ('vestibulum sed magna at nunc commodo placerat', 55, 'Felis libyca', 2, 94),
       ('felis ut at dolor', 61, 'Hystrix indica', 0, 44),
       ('maecenas rhoncus aliquam lacus morbi quis tortor id', 80, 'Francolinus coqui', 0, 47),
       ('scelerisque mauris sit amet eros suspendisse accumsan tortor quis', 44, 'Streptopelia senegalensis', 1, 28),
       ('suspendisse potenti nullam porttitor lacus at turpis donec posuere metus', 56, 'Leprocaulinus vipera', 0, 24),
       ('vel augue vestibulum rutrum rutrum', 12, 'Erinaceus frontalis', 0, 37),
       ('vel accumsan tellus nisi eu orci mauris lacinia sapien quis', 76, 'Vombatus ursinus', 0, 63),
       ('orci luctus et ultrices posuere cubilia curae donec pharetra magna', 30, 'Coendou prehensilis', 1, 10),
       ('placerat praesent', 62, 'Coendou prehensilis', 2, 18),
       ('pretium quis lectus suspendisse potenti in', 10, 'Bassariscus astutus', 2, 37),
       ('amet consectetuer adipiscing elit proin interdum mauris non ligula', 48, 'Papio cynocephalus', 2, 60),
       ('odio consequat varius integer ac leo pellentesque ultrices mattis odio', 4, 'Leptoptilos crumeniferus', 2, 58),
       ('non mauris morbi non', 12, 'Lama pacos', 2, 55),
       ('at dolor quis odio', 46, 'Diceros bicornis', 0, 36),
       ('sagittis dui vel nisl duis ac nibh fusce', 91, 'Ratufa indica', 2, 85),
       ('in hac', 39, 'Petaurus norfolcensis', 1, 99),
       ('hac habitasse platea dictumst etiam faucibus cursus', 4, 'Macropus eugenii', 0, 35),
       ('ac diam', 90, 'Ara macao', 1, 61),
       ('orci luctus et ultrices posuere cubilia', 41, 'Cercatetus concinnus', 2, 58),
       ('tristique est et tempus semper est quam pharetra magna', 5, 'Phascogale tapoatafa', 0, 50),
       ('nisi nam ultrices', 78, 'Ammospermophilus nelsoni', 1, 92),
       ('tortor risus dapibus augue vel accumsan tellus', 80, 'Acrantophis madagascariensis', 2, 36),
       ('tristique est et tempus semper est quam pharetra magna', 65, 'Aquila chrysaetos', 2, 32),
       ('diam id ornare imperdiet sapien urna pretium', 24, 'Speothos vanaticus', 1, 99),
       ('mi integer ac neque duis bibendum morbi', 43, 'Anser anser', 1, 7),
       ('id ornare imperdiet sapien urna pretium nisl', 76, 'Ovis orientalis', 0, 95),
       ('sagittis sapien cum sociis natoque', 38, 'Psophia viridis', 0, 91),
       ('vestibulum sed magna at nunc commodo placerat praesent blandit', 22, 'Lutra canadensis', 2, 25),
       ('amet sapien', 33, 'Zosterops pallidus', 0, 92),
       ('nullam varius nulla facilisi cras', 1, 'Anser anser', 1, 100),
       ('id sapien in sapien iaculis congue', 19, 'Macaca nemestrina', 1, 48),
       ('ac neque', 86, 'Bubulcus ibis', 1, 44),
       ('a suscipit nulla elit ac nulla', 29, 'Colobus guerza', 1, 10),
       ('quis augue luctus', 7, 'Equus hemionus', 2, 76),
       ('cum sociis natoque penatibus et magnis dis parturient montes', 99, 'Larus fuliginosus', 1, 33),
       ('tincidunt lacus', 14, 'Graspus graspus', 0, 55),
       ('tincidunt in leo maecenas pulvinar lobortis', 55, 'Mazama gouazoubira', 1, 10),
       ('et ultrices posuere', 86, 'Merops sp.', 2, 97),
       ('platea dictumst morbi vestibulum velit id', 40, 'Varanus sp.', 2, 52),
       ('libero nam dui proin leo odio porttitor id consequat in', 27, 'Uraeginthus granatina', 0, 8),
       ('etiam pretium', 68, 'Canis aureus', 0, 30),
       ('rutrum ac lobortis vel dapibus at', 50, 'Sauromalus obesus', 0, 82),
       ('sed tristique in tempus', 29, 'Capreolus capreolus', 2, 64),
       ('mi sit amet lobortis sapien sapien non', 19, 'Zenaida asiatica', 1, 11),
       ('tortor risus dapibus augue vel accumsan tellus', 61, 'Diomedea irrorata', 1, 99),
       ('porttitor lacus at turpis donec posuere metus', 67, 'Junonia genoveua', 0, 60),
       ('ultricies eu nibh quisque', 26, 'Sylvilagus floridanus', 2, 44),
       ('in porttitor pede', 68, 'Phalaropus lobatus', 0, 3),
       ('nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis', 26, 'Ursus maritimus', 0, 98),
       ('elit proin interdum mauris non ligula pellentesque', 54, 'Macaca mulatta', 1, 55),
       ('sed vestibulum sit amet cursus id turpis', 91, 'Bubalus arnee', 2, 43),
       ('ante ipsum primis in faucibus orci luctus et', 62, 'Mellivora capensis', 0, 91),
       ('vitae quam suspendisse potenti nullam porttitor lacus at', 27, 'Connochaetus taurinus', 1, 50),
       ('arcu sed augue', 42, 'Varanus salvator', 0, 100),
       ('luctus rutrum nulla tellus in sagittis dui vel nisl', 62, 'Zosterops pallidus', 2, 49),
       ('orci eget orci vehicula condimentum curabitur in', 81, 'Colobus guerza', 1, 5),
       ('mattis nibh ligula', 89, 'Gazella thompsonii', 2, 22),
       ('ac neque duis bibendum morbi non quam nec', 91, 'Varanus sp.', 0, 4),
       ('nulla nisl nunc nisl', 14, 'Sarkidornis melanotos', 0, 16),
       ('facilisi cras non velit nec nisi', 15, 'Odocoileus hemionus', 2, 80),
       ('vel ipsum praesent blandit lacinia erat vestibulum sed magna at', 78, 'Hystrix cristata', 2, 76),
       ('laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui', 53, 'Tachyglossus aculeatus', 0, 74),
       ('odio elementum eu interdum', 75, 'Theropithecus gelada', 0, 38),
       ('in hac habitasse platea dictumst morbi vestibulum velit id pretium', 64, 'Ardea cinerea', 0, 75),
       ('vehicula consequat morbi a ipsum integer', 94, 'Haliaetus vocifer', 1, 31),
       ('ipsum integer a nibh', 78, 'unavailable', 0, 22),
       ('quam sapien varius ut blandit non interdum in ante', 39, 'Tringa glareola', 1, 6),
       ('dui proin leo odio porttitor id consequat in consequat', 22, 'Larus sp.', 0, 75),
       ('semper porta volutpat quam pede lobortis ligula', 30, 'Tayassu pecari', 0, 81),
       ('felis ut at dolor quis odio consequat varius integer', 83, 'Macaca fuscata', 0, 22),
       ('aenean sit amet justo morbi ut odio cras', 42, 'unavailable', 2, 21),
       ('condimentum curabitur in libero ut massa volutpat convallis morbi odio', 97, 'Actophilornis africanus', 2, 95),
       ('pede morbi', 18, 'Leptoptilus dubius', 1, 39),
       ('mauris morbi non lectus aliquam sit', 40, 'Nyctanassa violacea', 2, 60),
       ('ullamcorper purus sit amet nulla quisque', 58, 'Dasypus novemcinctus', 0, 22),
       ('diam in magna', 53, 'Equus burchelli', 1, 84),
       ('luctus et ultrices', 55, 'Neotis denhami', 2, 69),
       ('tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', 60, 'Zenaida galapagoensis', 0,
        81),
       ('eros suspendisse accumsan tortor quis turpis sed', 41, 'Phalaropus lobatus', 0, 87),
       ('fermentum donec ut mauris eget', 47, 'Columba livia', 1, 31),
       ('lorem quisque ut erat curabitur gravida', 9, 'Chordeiles minor', 0, 39),
       ('curabitur convallis duis consequat', 38, 'Zalophus californicus', 1, 34),
       ('luctus tincidunt nulla mollis molestie lorem quisque', 2, 'Phalacrocorax albiventer', 0, 28),
       ('eu tincidunt in leo maecenas', 22, 'Pandon haliaetus', 0, 46),
       ('nunc purus phasellus in felis', 84, 'Creagrus furcatus', 0, 84),
       ('pede malesuada', 67, 'Estrilda erythronotos', 2, 89),
       ('id nisl venenatis lacinia aenean sit', 45, 'Scolopax minor', 0, 43),
       ('curae donec pharetra magna vestibulum aliquet ultrices erat tortor', 47, 'Ceratotherium simum', 0, 98),
       ('vel est', 9, 'Pan troglodytes', 2, 12),
       ('cras in purus eu magna vulputate luctus cum', 36, 'Genetta genetta', 1, 24),
       ('sem sed sagittis', 7, 'unavailable', 0, 99),
       ('bibendum morbi non quam nec', 22, 'Cracticus nigroagularis', 1, 17),
       ('neque aenean auctor gravida sem praesent id massa', 39, 'Lemur catta', 1, 23),
       ('platea dictumst', 96, 'Elephas maximus bengalensis', 0, 25),
       ('nulla sed accumsan felis ut at dolor quis odio', 73, 'Agama sp.', 1, 45),
       ('magna vestibulum aliquet ultrices', 66, 'Manouria emys', 0, 72),
       ('nibh in quis justo', 48, 'Tiliqua scincoides', 0, 50),
       ('sapien ut nunc vestibulum ante ipsum primis in', 16, 'Priodontes maximus', 0, 52),
       ('euismod scelerisque quam turpis', 18, 'Orcinus orca', 2, 100),
       ('placerat praesent blandit nam nulla', 79, 'Pedetes capensis', 2, 49),
       ('cursus urna ut', 55, 'Papio cynocephalus', 1, 28),
       ('nec sem duis aliquam convallis nunc proin at turpis a', 17, 'Sula dactylatra', 0, 84),
       ('rhoncus mauris enim leo', 56, 'Pandon haliaetus', 1, 77),
       ('ut ultrices vel augue vestibulum ante ipsum primis in faucibus', 81, 'Charadrius tricollaris', 2, 4),
       ('ut rhoncus aliquet pulvinar', 28, 'unavailable', 2, 23),
       ('praesent id massa id nisl venenatis lacinia aenean sit amet', 35, 'unavailable', 2, 44),
       ('placerat ante nulla justo aliquam quis turpis eget elit', 63, 'Larus dominicanus', 1, 23),
       ('ipsum dolor sit amet consectetuer adipiscing elit', 40, 'Chlidonias leucopterus', 2, 58),
       ('volutpat eleifend', 37, 'Columba livia', 0, 6),
       ('a nibh in quis justo maecenas rhoncus aliquam lacus', 79, 'Choloepus hoffmani', 1, 97),
       ('pellentesque volutpat dui maecenas tristique est et tempus', 10, 'Bassariscus astutus', 1, 33),
       ('vestibulum ante ipsum primis in faucibus orci', 33, 'Centrocercus urophasianus', 0, 46),
       ('nunc vestibulum ante ipsum primis', 53, 'Coluber constrictor', 2, 32),
       ('velit donec diam neque', 1, 'Tayassu pecari', 1, 32),
       ('nisl ut volutpat sapien', 4, 'Anas punctata', 1, 58),
       ('duis ac nibh fusce', 27, 'Morelia spilotes variegata', 1, 75),
       ('pede posuere nonummy integer non', 61, 'Canis lupus', 0, 26),
       ('congue eget semper rutrum', 63, 'Cygnus buccinator', 0, 75),
       ('nascetur ridiculus mus etiam vel', 10, 'Amblyrhynchus cristatus', 1, 78),
       ('elit ac nulla sed', 42, 'Eudromia elegans', 2, 71),
       ('interdum mauris non', 47, 'unavailable', 2, 70),
       ('morbi vestibulum velit id', 33, 'Papio cynocephalus', 0, 22),
       ('amet lobortis sapien sapien non mi integer ac neque', 61, 'Oxybelis fulgidus', 1, 14),
       ('mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', 41, 'Macaca fuscata', 0, 89),
       ('feugiat et eros', 34, 'Lycaon pictus', 1, 77),
       ('luctus et ultrices posuere', 13, 'Hydrochoerus hydrochaeris', 2, 100),
       ('eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', 70, 'Cracticus nigroagularis', 1,
        100),
       ('ante vivamus tortor duis', 16, 'Meleagris gallopavo', 1, 98),
       ('nisl duis', 68, 'Carduelis uropygialis', 0, 13),
       ('egestas metus aenean fermentum donec ut mauris eget massa tempor', 91, 'Macaca mulatta', 0, 51),
       ('id mauris vulputate elementum nullam', 76, 'Tayassu pecari', 0, 13),
       ('amet consectetuer adipiscing elit proin interdum mauris non ligula', 33, 'Phalaropus fulicarius', 0, 82),
       ('tempus semper est quam pharetra', 32, 'Amblyrhynchus cristatus', 0, 4),
       ('viverra eget', 32, 'Drymarchon corias couperi', 2, 72),
       ('ac lobortis vel dapibus at diam nam tristique tortor', 40, 'Ovis canadensis', 2, 60),
       ('integer ac neque duis bibendum morbi non', 47, 'Rhea americana', 2, 92),
       ('quisque porta volutpat erat', 88, 'unavailable', 0, 63),
       ('tortor sollicitudin mi sit amet lobortis sapien sapien non', 100, 'Mephitis mephitis', 2, 90),
       ('luctus ultricies eu nibh quisque id', 25, 'Actophilornis africanus', 0, 13),
       ('est risus', 64, 'Pan troglodytes', 0, 27),
       ('magna ac consequat metus sapien', 84, 'Ephippiorhynchus mycteria', 0, 54),
       ('curae mauris viverra diam vitae', 60, 'Kobus vardonii vardoni', 1, 55),
       ('rutrum neque aenean auctor gravida sem praesent', 83, 'Cebus apella', 0, 18),
       ('rutrum rutrum neque aenean auctor', 55, 'Irania gutteralis', 2, 97),
       ('aliquet pulvinar sed', 96, 'Dasyurus viverrinus', 2, 24),
       ('nunc vestibulum ante ipsum primis', 100, 'Macropus eugenii', 0, 30),
       ('turpis a pede posuere', 19, 'Loris tardigratus', 2, 66),
       ('amet eleifend pede libero quis', 92, 'Tiliqua scincoides', 1, 85),
       ('curae duis faucibus accumsan odio curabitur', 68, 'Aonyx cinerea', 1, 100),
       ('urna pretium', 86, 'Limosa haemastica', 2, 63),
       ('iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 81, 'Ceryle rudis', 1, 22),
       ('pede posuere nonummy integer non velit donec diam neque', 71, 'Sciurus vulgaris', 0, 96),
       ('turpis nec euismod scelerisque quam turpis', 55, 'Tauraco porphyrelophus', 1, 70),
       ('enim sit amet nunc', 79, 'Loxodonta africana', 2, 5),
       ('lacinia erat vestibulum sed magna at nunc commodo', 98, 'Bugeranus caruncalatus', 1, 5),
       ('tempus sit amet sem fusce consequat nulla nisl nunc', 44, 'Plegadis falcinellus', 2, 90),
       ('non pretium quis lectus suspendisse potenti in eleifend quam', 39, 'Francolinus coqui', 0, 63),
       ('neque aenean auctor', 73, 'Myotis lucifugus', 2, 81),
       ('ultrices enim lorem ipsum dolor sit amet consectetuer', 22, 'Choloepus hoffmani', 1, 85),
       ('turpis a pede posuere nonummy integer non', 2, 'Bassariscus astutus', 2, 94),
       ('nulla ac enim in tempor turpis nec euismod scelerisque', 93, 'Calyptorhynchus magnificus', 1, 15),
       ('felis fusce posuere', 27, 'Kobus vardonii vardoni', 0, 18),
       ('sapien varius ut blandit non', 91, 'Ammospermophilus nelsoni', 0, 84),
       ('cras in purus eu magna vulputate luctus cum', 90, 'Vulpes vulpes', 0, 26),
       ('ipsum primis', 3, 'Pycnonotus nigricans', 2, 1),
       ('ac est lacinia', 18, 'Corvus brachyrhynchos', 1, 3),
       ('in hac habitasse platea dictumst morbi vestibulum velit id', 30, 'Dendrocitta vagabunda', 1, 90),
       ('vivamus in felis eu sapien cursus vestibulum proin eu', 67, 'Connochaetus taurinus', 0, 77),
       ('elementum nullam varius nulla facilisi cras non velit nec', 78, 'Aonyx cinerea', 1, 76),
       ('mauris eget massa', 2, 'Phalaropus lobatus', 1, 3),
       ('mattis pulvinar nulla', 51, 'Sciurus vulgaris', 0, 67),
       ('platea dictumst morbi vestibulum velit', 5, 'Leprocaulinus vipera', 2, 66),
       ('vulputate nonummy maecenas tincidunt lacus at velit vivamus', 94, 'Coluber constrictor', 0, 49),
       ('justo sit amet', 5, 'Melophus lathami', 1, 66),
       ('fusce posuere felis sed lacus morbi sem', 85, 'Dicrostonyx groenlandicus', 0, 1),
       ('vulputate justo in blandit ultrices', 69, 'Gorilla gorilla', 1, 63),
       ('orci luctus et ultrices', 16, 'Dasyurus viverrinus', 2, 7),
       ('vulputate ut ultrices vel', 80, 'Bubalornis niger', 0, 16),
       ('lectus pellentesque at nulla suspendisse potenti cras in', 56, 'Lepus arcticus', 0, 18),
       ('imperdiet sapien urna pretium', 35, 'Passer domesticus', 1, 95),
       ('nullam porttitor lacus at turpis donec', 84, 'Megaderma spasma', 2, 29),
       ('erat quisque erat', 3, 'Ovis ammon', 2, 1),
       ('et ultrices posuere', 20, 'Coluber constrictor foxii', 1, 98),
       ('sit amet nulla quisque arcu', 4, 'Catharacta skua', 1, 87),
       ('quis augue luctus tincidunt nulla mollis', 24, 'Halcyon smyrnesis', 2, 81),
       ('semper porta volutpat quam pede lobortis ligula sit', 70, 'Phalacrocorax carbo', 2, 31),
       ('sed sagittis nam congue', 1, 'Orcinus orca', 0, 35),
       ('vestibulum ante ipsum primis', 38, 'Tayassu tajacu', 0, 73),
       ('in libero ut massa volutpat convallis morbi odio odio', 52, 'Panthera tigris', 1, 60),
       ('lorem vitae mattis', 79, 'Phalacrocorax niger', 0, 78),
       ('nisl ut volutpat sapien arcu sed augue aliquam', 98, 'Dusicyon thous', 1, 88),
       ('neque sapien', 66, 'Madoqua kirkii', 2, 74),
       ('donec vitae nisi nam', 63, 'Rhea americana', 2, 98),
       ('odio elementum eu', 92, 'Vulpes vulpes', 1, 3),
       ('non lectus aliquam sit amet', 56, 'Vanellus armatus', 2, 49),
       ('sapien quis libero nullam sit amet turpis elementum', 85, 'Connochaetus taurinus', 0, 3),
       ('lectus in est risus auctor sed tristique in', 38, 'Buteo galapagoensis', 2, 25),
       ('ipsum primis in', 56, 'Carduelis pinus', 2, 2),
       ('congue eget semper', 34, 'Macropus rufogriseus', 0, 27),
       ('lacinia aenean sit amet justo morbi ut', 89, 'Paradoxurus hermaphroditus', 1, 67),
       ('eu magna', 81, 'Callipepla gambelii', 0, 7),
       ('ac consequat metus sapien ut nunc vestibulum ante', 78, 'Tadorna tadorna', 0, 82),
       ('mauris enim leo rhoncus', 28, 'Antechinus flavipes', 2, 17),
       ('accumsan felis ut at dolor quis odio consequat varius integer', 25, 'Lycosa godeffroyi', 0, 71),
       ('nulla neque', 14, 'Pelecans onocratalus', 0, 34),
       ('lobortis vel dapibus at diam nam tristique tortor eu', 63, 'Bassariscus astutus', 1, 76),
       ('nam congue', 76, 'Uraeginthus angolensis', 0, 63),
       ('quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', 77, 'Cebus apella', 2, 63),
       ('suscipit nulla', 59, 'Larus novaehollandiae', 2, 15),
       ('hac habitasse platea dictumst etiam', 74, 'Oryx gazella', 2, 59),
       ('lacus curabitur at ipsum ac tellus semper interdum mauris', 32, 'Thalasseus maximus', 1, 85),
       ('tempus semper est quam pharetra magna ac', 35, 'Chauna torquata', 0, 51),
       ('tortor risus dapibus augue vel accumsan tellus nisi eu orci', 69, 'Physignathus cocincinus', 1, 97),
       ('congue vivamus metus arcu adipiscing molestie', 12, 'Kobus defassa', 0, 64),
       ('morbi quis tortor', 17, 'Acrobates pygmaeus', 2, 6),
       ('risus auctor sed', 77, 'Himantopus himantopus', 1, 15),
       ('venenatis non sodales', 51, 'Laniarius ferrugineus', 0, 83),
       ('at turpis a pede', 78, 'unavailable', 2, 72),
       ('sapien cursus vestibulum proin eu', 51, 'Sarkidornis melanotos', 2, 45),
       ('tristique est et tempus semper est quam pharetra magna', 60, 'Phoenicopterus ruber', 2, 83),
       ('vestibulum vestibulum ante ipsum primis in faucibus orci luctus', 56, 'Globicephala melas', 1, 83),
       ('pellentesque eget nunc donec', 97, 'Tamiasciurus hudsonicus', 1, 29),
       ('pede morbi porttitor lorem id ligula suspendisse ornare consequat', 99, 'Sylvilagus floridanus', 1, 88),
       ('rutrum at lorem integer tincidunt ante vel', 85, 'Anas bahamensis', 0, 68),
       ('vestibulum ante ipsum primis in faucibus orci luctus', 39, 'Globicephala melas', 0, 67),
       ('cras pellentesque volutpat dui maecenas tristique est et tempus', 63, 'Panthera pardus', 2, 11),
       ('cras mi', 78, 'Cyrtodactylus louisiadensis', 0, 93),
       ('odio consequat varius integer ac leo pellentesque ultrices mattis odio', 33, 'Passer domesticus', 1, 10),
       ('adipiscing molestie hendrerit at vulputate', 58, 'Meles meles', 2, 19),
       ('rhoncus aliquam lacus morbi quis tortor', 72, 'Streptopelia senegalensis', 2, 16),
       ('lorem ipsum dolor sit amet consectetuer adipiscing', 48, 'Macropus robustus', 1, 47),
       ('dolor vel est', 10, 'Varanus salvator', 2, 42),
       ('vel nulla eget eros elementum pellentesque quisque porta', 59, 'Haematopus ater', 0, 6),
       ('blandit mi in porttitor pede justo eu massa donec dapibus', 100, 'Varanus salvator', 0, 29),
       ('lectus suspendisse potenti in eleifend', 21, 'Tyto novaehollandiae', 1, 20),
       ('varius ut blandit non interdum', 37, 'Lorythaixoides concolor', 1, 12),
       ('sit amet turpis elementum ligula vehicula consequat morbi', 16, 'Francolinus leucoscepus', 1, 22),
       ('ut dolor morbi vel lectus', 74, 'Colobus guerza', 2, 23),
       ('accumsan odio curabitur convallis duis consequat dui nec nisi volutpat', 77, 'Ratufa indica', 2, 20),
       ('molestie nibh in lectus pellentesque at nulla suspendisse', 13, 'Arctogalidia trivirgata', 1, 82),
       ('ut erat curabitur gravida nisi at nibh in', 50, 'Nasua nasua', 0, 2),
       ('ut at dolor quis', 49, 'Tapirus terrestris', 1, 6),
       ('nisi volutpat', 86, 'Creagrus furcatus', 2, 50),
       ('eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', 22, 'Bison bison', 1, 36),
       ('velit donec diam neque vestibulum', 56, 'Cordylus giganteus', 1, 87),
       ('orci eget orci vehicula condimentum curabitur in', 33, 'Alopex lagopus', 0, 64),
       ('vulputate nonummy maecenas tincidunt lacus at', 3, 'Helogale undulata', 1, 5),
       ('purus aliquet at feugiat non pretium', 34, 'Eremophila alpestris', 0, 62),
       ('ut massa quis', 39, 'Vanellus armatus', 0, 77),
       ('in felis donec semper sapien a libero nam', 78, 'Mellivora capensis', 1, 39),
       ('curabitur convallis duis consequat', 31, 'Pavo cristatus', 1, 88),
       ('posuere cubilia curae', 28, 'Motacilla aguimp', 0, 72),
       ('ultrices erat tortor sollicitudin mi sit amet', 4, 'Phoca vitulina', 0, 44),
       ('at nibh in', 9, 'Coluber constrictor', 2, 38),
       ('pede ac diam cras pellentesque volutpat dui maecenas tristique', 82, 'Uraeginthus bengalus', 0, 13),
       ('mi sit amet lobortis sapien sapien non mi integer', 61, 'Charadrius tricollaris', 1, 25),
       ('duis at velit eu est congue elementum in', 51, 'Varanus salvator', 2, 62),
       ('quisque id justo sit amet sapien dignissim', 12, 'Naja nivea', 2, 55),
       ('sed magna at nunc commodo placerat praesent blandit', 42, 'Ateles paniscus', 1, 75),
       ('consequat in consequat ut nulla sed accumsan felis', 34, 'Dusicyon thous', 0, 49),
       ('aliquam convallis', 48, 'Sus scrofa', 2, 63),
       ('quam sapien varius ut blandit non interdum in', 54, 'Salvadora hexalepis', 2, 52),
       ('ante ipsum primis in faucibus orci luctus et ultrices', 90, 'Corvus albicollis', 2, 71),
       ('id massa id nisl venenatis lacinia aenean sit amet justo', 72, 'Nucifraga columbiana', 2, 31),
       ('condimentum id luctus', 59, 'Nyctereutes procyonoides', 1, 55),
       ('proin interdum mauris non ligula pellentesque ultrices', 57, 'Streptopelia decipiens', 2, 58),
       ('nonummy maecenas', 5, 'Pelecanus occidentalis', 0, 38),
       ('vulputate nonummy', 12, 'Ictonyx striatus', 0, 89),
       ('enim blandit mi in porttitor pede', 3, 'Chlidonias leucopterus', 0, 87),
       ('pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus', 15, 'Antidorcas marsupialis', 0,
        13),
       ('ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', 16, 'Phalacrocorax carbo', 2,
        11),
       ('natoque penatibus et magnis dis', 47, 'Marmota monax', 0, 14),
       ('pellentesque volutpat dui maecenas tristique', 11, 'Cebus apella', 1, 33),
       ('tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 31, 'Aquila chrysaetos', 0, 35),
       ('elit proin', 96, 'Bradypus tridactylus', 1, 92),
       ('fermentum donec ut mauris eget massa tempor convallis nulla neque', 34, 'Heloderma horridum', 1, 39),
       ('ac leo pellentesque ultrices mattis odio donec vitae nisi', 58, 'Mazama americana', 1, 67),
       ('eget massa tempor convallis nulla neque libero', 88, 'Himantopus himantopus', 0, 76),
       ('magnis dis parturient', 19, 'Oryx gazella callotis', 2, 69),
       ('feugiat non pretium quis lectus suspendisse potenti in eleifend', 98, 'Nannopterum harrisi', 1, 38),
       ('in magna', 21, 'Eutamias minimus', 0, 90),
       ('lacinia eget tincidunt eget tempus', 61, 'Falco peregrinus', 2, 47),
       ('vel dapibus at diam nam tristique', 32, 'Lycosa godeffroyi', 0, 11),
       ('accumsan tellus nisi eu orci mauris lacinia', 23, 'Milvago chimachima', 2, 34),
       ('ultrices posuere', 16, 'Chlidonias leucopterus', 2, 73),
       ('morbi sem mauris', 24, 'Upupa epops', 2, 56),
       ('lobortis vel', 90, 'Physignathus cocincinus', 1, 21),
       ('blandit non interdum in ante vestibulum ante ipsum primis in', 45, 'Gymnorhina tibicen', 1, 35),
       ('sed augue aliquam erat volutpat in congue etiam justo', 57, 'Cacatua tenuirostris', 0, 65),
       ('ut odio cras', 37, 'Alligator mississippiensis', 1, 14),
       ('ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 17, 'Lasiodora parahybana', 2, 17),
       ('non quam nec dui luctus rutrum nulla', 91, 'Gazella thompsonii', 0, 20),
       ('curae duis faucibus', 75, 'Hydrochoerus hydrochaeris', 0, 29),
       ('pede morbi porttitor lorem id ligula suspendisse', 97, 'Dendrohyrax brucel', 0, 12),
       ('sem mauris', 8, 'Bradypus tridactylus', 0, 15),
       ('nullam sit amet turpis elementum ligula vehicula consequat morbi a', 49, 'Rhea americana', 2, 60),
       ('in hac habitasse platea dictumst morbi', 9, 'Macropus rufus', 1, 88),
       ('auctor gravida sem praesent id massa id nisl venenatis lacinia', 98, 'Bison bison', 2, 70),
       ('ornare consequat lectus in est', 5, 'Catharacta skua', 0, 44),
       ('suspendisse ornare consequat lectus', 84, 'Myrmecophaga tridactyla', 2, 40),
       ('vestibulum sed magna at nunc commodo placerat praesent blandit nam', 29, 'Semnopithecus entellus', 1, 100),
       ('fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet', 81, 'Potorous tridactylus', 2, 57),
       ('in faucibus orci', 75, 'Cacatua tenuirostris', 0, 78),
       ('sagittis sapien cum sociis natoque', 13, 'Crotaphytus collaris', 0, 78),
       ('fermentum justo nec condimentum', 39, 'Acrantophis madagascariensis', 2, 51),
       ('mauris viverra diam vitae quam', 45, 'Vanessa indica', 0, 36),
       ('hac habitasse platea dictumst maecenas', 69, 'Macropus rufogriseus', 0, 37),
       ('dis parturient montes nascetur ridiculus mus', 82, 'unavailable', 1, 26),
       ('leo pellentesque ultrices mattis odio donec vitae nisi', 71, 'Tayassu pecari', 1, 97),
       ('donec dapibus duis at', 19, 'Spizaetus coronatus', 0, 27),
       ('ante nulla justo aliquam quis turpis eget', 1, 'Columba livia', 2, 96),
       ('luctus et ultrices posuere cubilia curae', 65, 'Anastomus oscitans', 0, 22),
       ('pretium iaculis diam erat fermentum', 32, 'Ursus maritimus', 1, 30),
       ('in est risus auctor sed', 30, 'Canis aureus', 2, 57),
       ('faucibus orci luctus et ultrices posuere cubilia curae', 31, 'Scolopax minor', 2, 85),
       ('sapien sapien non mi integer ac neque duis bibendum morbi', 73, 'Pelecanus conspicillatus', 2, 22),
       ('elementum in hac habitasse platea dictumst morbi vestibulum velit id', 12, 'Cebus apella', 2, 87),
       ('velit vivamus vel', 47, 'Cordylus giganteus', 1, 60),
       ('amet consectetuer adipiscing elit proin interdum mauris non', 42, 'Perameles nasuta', 2, 70),
       ('amet sapien dignissim', 80, 'Lemur catta', 1, 59),
       ('hac habitasse platea', 52, 'unavailable', 0, 45),
       ('arcu sed', 66, 'Tragelaphus strepsiceros', 2, 24),
       ('ligula suspendisse ornare consequat lectus in est risus auctor', 74, 'Chlidonias leucopterus', 1, 99),
       ('eget vulputate ut ultrices vel augue vestibulum ante ipsum', 76, 'Trachyphonus vaillantii', 1, 35),
       ('id turpis integer aliquet massa', 89, 'Boa caninus', 1, 29),
       ('vel augue vestibulum ante ipsum', 64, 'Spilogale gracilis', 0, 31),
       ('mauris laoreet ut rhoncus aliquet pulvinar sed', 94, 'Diomedea irrorata', 2, 69),
       ('curae donec pharetra magna vestibulum aliquet ultrices erat', 20, 'Zosterops pallidus', 1, 59),
       ('nam dui proin leo odio porttitor id consequat in consequat', 8, 'Lepus arcticus', 0, 74),
       ('accumsan odio', 53, 'Limnocorax flavirostra', 0, 50),
       ('aliquam convallis nunc', 95, 'Dasyprocta leporina', 1, 98),
       ('elementum pellentesque quisque porta volutpat erat', 97, 'Phascogale calura', 0, 96),
       ('amet sapien dignissim vestibulum', 75, 'Philetairus socius', 0, 27),
       ('ac tellus semper interdum mauris ullamcorper', 23, 'Coendou prehensilis', 1, 1),
       ('cum sociis natoque', 72, 'Coendou prehensilis', 0, 72),
       ('ultrices libero non mattis pulvinar', 35, 'Lemur fulvus', 2, 15),
       ('augue a suscipit nulla elit ac nulla sed vel enim', 1, 'Alcelaphus buselaphus cokii', 0, 93),
       ('amet sapien dignissim vestibulum vestibulum ante ipsum', 93, 'unavailable', 1, 42),
       ('morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', 99, 'Canis lupus lycaon', 2, 50),
       ('in consequat ut nulla sed accumsan felis ut', 26, 'Pseudoleistes virescens', 1, 7),
       ('lobortis ligula sit amet eleifend pede libero quis orci', 10, 'Macropus giganteus', 2, 65),
       ('consequat dui nec nisi volutpat', 16, 'Kobus defassa', 2, 38),
       ('habitasse platea dictumst', 64, 'Alligator mississippiensis', 2, 66),
       ('quisque porta volutpat erat quisque erat eros viverra', 54, 'Zalophus californicus', 0, 46),
       ('donec ut', 29, 'Zosterops pallidus', 1, 94),
       ('faucibus orci luctus et ultrices posuere cubilia', 93, 'Larus dominicanus', 1, 84),
       ('elementum pellentesque quisque porta', 65, 'Phoeniconaias minor', 1, 100),
       ('tristique est', 99, 'Canis aureus', 2, 3),
       ('at ipsum ac tellus', 2, 'Canis mesomelas', 0, 29),
       ('montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum', 24, 'Hystrix indica', 0, 44),
       ('habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 88, 'Canis aureus', 1, 66),
       ('pulvinar lobortis est', 88, 'Cyrtodactylus louisiadensis', 2, 9),
       ('nascetur ridiculus mus etiam vel augue vestibulum', 32, 'Callorhinus ursinus', 1, 58),
       ('risus semper porta volutpat quam pede lobortis ligula sit', 34, 'Canis aureus', 0, 46),
       ('nisl aenean lectus pellentesque eget', 23, 'Papilio canadensis', 2, 97),
       ('nisi venenatis tristique fusce congue diam id', 65, 'Bos taurus', 1, 11),
       ('in faucibus orci luctus et', 13, 'Gyps fulvus', 0, 10),
       ('libero quis orci nullam', 76, 'Catharacta skua', 2, 51),
       ('tortor sollicitudin', 37, 'Corvus brachyrhynchos', 1, 48),
       ('sapien iaculis congue vivamus metus arcu adipiscing molestie', 32, 'Panthera pardus', 0, 47),
       ('vulputate vitae', 41, 'Corallus hortulanus cooki', 0, 34),
       ('id turpis integer aliquet massa id lobortis convallis tortor risus', 6, 'Ctenophorus ornatus', 2, 11),
       ('vestibulum sed', 65, 'Elephas maximus bengalensis', 1, 48),
       ('diam in magna bibendum imperdiet', 25, 'Bubalornis niger', 0, 55),
       ('rutrum neque aenean auctor gravida sem praesent id massa id', 61, 'Anathana ellioti', 1, 22),
       ('maecenas ut', 10, 'Oryx gazella callotis', 0, 67),
       ('at nunc commodo placerat praesent blandit nam nulla integer', 16, 'Corvus brachyrhynchos', 0, 15),
       ('et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur', 65, 'Bubalornis niger', 1, 23),
       ('est lacinia nisi venenatis tristique', 37, 'Ctenophorus ornatus', 0, 4),
       ('commodo placerat praesent blandit nam', 6, 'Dasyurus maculatus', 2, 17),
       ('varius integer ac leo pellentesque ultrices mattis odio donec vitae', 22, 'Loxodonta africana', 2, 42),
       ('eu orci mauris lacinia', 35, 'Buteo galapagoensis', 0, 46),
       ('consequat metus', 36, 'Kobus leche robertsi', 0, 70),
       ('mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 72, 'Mazama gouazoubira', 0, 84),
       ('lorem ipsum dolor sit amet consectetuer adipiscing elit', 77, 'Lamprotornis nitens', 1, 66),
       ('ridiculus mus etiam vel augue vestibulum', 69, 'Tamiasciurus hudsonicus', 2, 34),
       ('rhoncus sed vestibulum sit amet cursus', 65, 'Lophoaetus occipitalis', 0, 92),
       ('eleifend pede libero quis', 27, 'Phalacrocorax niger', 2, 43),
       ('in quis justo', 26, 'Bassariscus astutus', 1, 24),
       ('blandit lacinia erat vestibulum sed magna at nunc', 81, 'Balearica pavonina', 2, 3),
       ('eros viverra eget', 78, 'Mabuya spilogaster', 0, 42),
       ('ut volutpat sapien arcu', 58, 'Uraeginthus bengalus', 2, 32),
       ('a pede posuere nonummy integer non velit donec diam neque', 4, 'Felis chaus', 0, 23),
       ('potenti cras in purus eu magna vulputate luctus', 61, 'Ardea golieth', 2, 7),
       ('nisl venenatis lacinia aenean sit amet justo morbi', 37, 'Anas bahamensis', 0, 1),
       ('leo odio condimentum id', 14, 'Psittacula krameri', 1, 77);
-- Join table
insert into projects_tasks (project_id, tasks_id) select
project_id, id from tasks;
